### ISSUE TITLE
Template para pandoc

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abntex/abntex2#111]
```
Which component is your suggestion addressed to?
[ ] class
[ ] packages
[ ] bibliography style
[ ] documentation
[ ] examples
[x] other: template

What is you suggestion?
Template tex para utilizar junto ao pandoc ao converter ou criar um novo 
arquivo.

Additional information:
Com este template seria fácil de se criar conteúdo por exemplo utilizando 
markdown ficaria simples a leitura do texto e usando o template aplicar e criar 
pdf, tex ou outro formato que o pandoc ofereça suporte a conversão e 
criação com os padrões abnt.
```

Original issue reported on code.google.com by `lamarcwa...@gmail.com` on 10 Apr 2014 at 8:10

**Comment by edusantana** [comment]
Oi Pessoal, quando comecei o [limarka](https://github.com/abntex/limarka) eu fiz algo similar com essa proposta. Mas depois percebi que o resultado era muito difícil de dar suporte. Então resolvi descartar por completo todo o template do pandoc e elaborar um novo template baseado nos códigos do abntex2.

Desse forma o resultado é um código latex mais parecido com o da comunidade do abntex, sendo possível comparar os resultados com mais facilidade.
