### ISSUE TITLE
Template HTML para Pandoc

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abntex/abntex2#122]
```
Which component is your suggestion addressed to?
[ ] class
[ ] packages
[ ] bibliography style
[ ] documentation
[ ] examples
[X] other: template

What is you suggestion?
Template HTML para utilizar junto ao template LaTeX do Pandoc ao converter ou 
criar um novo arquivo.

Additional information:
Com este template seria fácil de se criar páginas HTML "equivalentes" ao 
código LaTeX gerado pelo Pandoc. As normas da ABNT neste caso seriam então 
posteriormente regradas por um arquivo CSS.
```

Original issue reported on code.google.com by `dudekt...@gmail.com` on 23 Jun 2014 at 10:57

**Comment by edusantana** [comment]
Olha, eu acho que a elaboração de um template para pandoc é algo um pouco mais complexo, que merece um projeto a parte.
Eu proponho que esse issue e #121 sejam fechados, e não implementados nesse repositório.

No momento, estou trabalhando apenas com o modelo de trabalho acadêmico, quem tiver interesse nessa temática poderá contribuir ou acessar https://github.com/abntex/trabalho-academico-pandoc-abntex2

**Comment by laurocesar** [comment]
Fechado devido a iniciativa do projeto https://github.com/abntex/limarka
