### ISSUE TITLE
mudar projeto para github ou outro repositório...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abntex/abntex2#141]
```
Google Code, o serviço de hospedagem de projetos do Google, está sendo 
desligado. Segundo o Google Open Source Blog, a empresa percebeu que o recurso 
simplesmente não é mais necessário e portanto, será desativado. Quem possui 
projetos hospedados lá, deve usar uma ferramenta do próprio Google para 
migrar para o GitHub, outro importante celeiro de projetos de código aberto.

http://www.techtudo.com.br/noticias/noticia/2015/03/google-code-vai-acabar-saiba
-exportar-codigos-para-o-github.html

```

Original issue reported on code.google.com by `admwag...@admwagner.com.br` on 13 Mar 2015 at 9:58

**Comment by laurocesar** [comment]
Importação do GoogleCode para o Github concluída!
Migração da wiki do GoogleCode para o Github concluída!
Inclusão na licença, página inicial e ignores do git (traduzidos do Mercurial) concluídas!

Agora falta ajustar as wikis e as issues

**Comment by laurocesar** [comment]
Favor atualizar o status na migração nesta página da wiki: [página da wiki](https://github.com/abntex/abntex2/wiki//Migra%C3%A7%C3%A3o-da-Wiki)
