### ISSUE TITLE
Problema com o tamanho da fonte das citações

### ISSUE THREAD

**Issue by gvillalta99** [abntex/abntex2#145]
Olá estou usando o `abntex2cite` para gerar as citações do meu painel, mas o tamanho da fonte das citações fica praticamente ilegível.

Meu documento é basicamente o seguinte:

````latex
\documentclass[a0,portrait]{a0poster}
\usepackage[brazil]{babel}
\usepackage[utf8]{inputenc}
\usepackage[alf]{abtex2cite}
\begin{document}

\bibliography{bibfile}
\end{document}
````

Tentei alterar o commando `\scriptsize` para um tamanho normal, não funcionou.

Tentei fazer o seguinte:

````latex
\documentclass[a0,portrait]{a0poster}
\usepackage[brazil]{babel}
\usepackage[utf8]{inputenc}
\usepackage[alf]{abtex2cite}
\begin{document}
{\normalsize \bibliography{bibfile}}
\end{document}
````

Sem sucesso.

Para se dar uma ideia da discrepância de tamanho eu tirei esse screenshot:
![captura de tela de 2015-05-05 20 30 04](https://cloud.githubusercontent.com/assets/396968/7484957/9193de94-f365-11e4-86c1-2eba8430e83a.png)

Por acaso, vocês alguma sugestão de como eu posso aumentar o tamanho da fonte das referências bibliográficas?

Agradeço desde já.

**Comment by laurocesar** [comment]
Caro @gvillalta99, em tese, você poderia alterar o comando ``\ABCIscriptfont`` com o tamanho de fonte que você quer. Faça o teste e veja se é o caso.

Na linha 740 do arquivo https://github.com/abntex/abntex2/blob/master/tex/latex/abntex2/abntex2cite.sty consta isto:

```
     \let\ABCIscriptfont\scriptsize
```

**Comment by gvillalta99** [comment]
@laurocesar eu tentei o seguinte no meu arquivo tex:

```
\let\ABCIscriptfont\normalsize
```

Mas não funcionou.
Eu dei um jeito, não utilizei a `abntex2`, mas funcionou.

Obrigado.
