### ISSUE TITLE
Lyx Não Funciona

### ISSUE THREAD

**Issue by JohnRobson** [abntex/abntex2#146]
Pessoal, primeiro quero dar os parabéns pelo projeto, eu já uso o ABNTeX desde 2009 e reescrever tudo como vcs fizeram realmente foi um nobre trabalho.

Estou tentando usar esta nova versão no LyX, peguei o último Layout (https://abntex2.googlecode.com/hg/contrib/lyx/abntex2.layout) e instalei no LyX

Fiz a capa e deu certo, depois foi inserir um capítulo e deram estes 2 erros:

```
1) {/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]

! Missing number, tre

ated as zero.

<to be read again>

\relax

l.25 \chapter{capitulo}

A number should have been here; I inserted `0'.

(If you can't figure out why I needed to see a number,

look up `weird error' in the index to The TeXbook.)
```
```
2) ! Illegal unit of measure (pt inserted).

<to be read again>

\relax

l.25 \chapter{capitulo}

Dimensions can be in units of em, ex, in, pt, pc,

cm, mm, dd, cc, nd, nc, bp, or sp; but yours is a new one!

I'll assume that you meant to say pt, for printer's points.

To recover gracefully from this error, it's best to

delete the erroneous units; e.g., type `2' to delete

two letters. (See Chapter 27 of The TeXbook.)
```

O logo inteiro está aqui:  https://paste.debian.net/180716/ tb Anexei o arquivo aqui: http://www.pastefile.com/WAYzmW

Alguém tem alguma ideia?

Obrigado,
John

**Comment by laurocesar** [comment]
Caro @sggranja , poderia ajudar-nos nessa questão sobre LyX? Obrigado!

**Comment by sggranja** [comment]
Olá JohnRobson, poderia informar-nos qual ramo do LyX está usando? O 2.0,X ou o 2.1.X?
Não consegui ver os arquivos de log que disse que estavam nos links.

Você poderia incluir o arquivo LyX que criou para podermos testar?

Silvio.

**Comment by sggranja** [comment]
JohnRobson,
Por algum acaso, você definiu a data no preâmbulo ou no corpo do texto do LyX?

**Comment by JohnRobson** [comment]
Olá Silvio, obrigado pelas respostas. Sim, eu segui todos os passos, eu já tenho alguma experiência.

Eu decidir usar o LaTeX puro mesmo pq precisava concluir um trabalho logo, mas vou olhar o LyX novamente; acho que um bom layout no LyX vai popularizar muito o ABNTeX.
