### ISSUE TITLE
Chamada numérica utilizando erroneamente colchetes ao invés dos formatos permitidos.

### ISSUE THREAD

**Issue by kerscher** [abntex/abntex2#147]
# Problema
Ao utilizar o estilo bibliográfico `abntex2-num`, o documento gerado incluí as chamadas no texto como [n], ao invés do correto (n) ou apenas <sup>n</sup> . Ver a seção 6.2.2 da NBR 10520:2002.
Note que o problema não ocorre ao usar o pacote `abntex2cite`.

# Solução possível

1. Alterar `abntex2-num` para usar parênteses ao invés de colchetes.
2. Criar um estilo `abntex2-num-sup` para o formato <sup>n</sup> de expoentes.

Como não há restrição a família tipográfica, apenas aos glifos, recomendo que no caso de parênteses o trecho inteiro esteja num bloco `textsc`. Isso marcaria semanticamente a introdução como referência ao invés de comentário do autor no seu próprio texto.

**Comment by kerscher** [comment]
No caso da inclusão de expoentes, uma solução separada seria criar uma opção `num-sup` ao pacote `abntex2cite` que altera as indicações em todo o documento.

Ver também #148 nesse caso.

**Comment by ycherem** [comment]
Pelo menos na última versão já há inserção de parênteses automaticamente. Ver também seção 4.1.4 do manual `abntex2cite.pdf`

**Comment by kerscher** [comment]
@ycherem, o problema não é usando `abntex2cite`, e sim o `abntex2-num` isoladamente como parâmetro para `\bibliographystyle`. A última versão altera isso, ou não há controle sobre esse elemento sem o pacote de citação?

**Comment by ycherem** [comment]
Existe o pacote para citação, e existe o estilo bibliográfico. Veja a seção
4.1 da documentação -- abntex2cite.pdf



Youssef Cherem
________________
!المسيح قام! حقاً قام

2015-06-01 19:37 GMT-03:00 Yghor Kerscher <notifications@github.com>:

**Comment by kerscher** [comment]
O que estou dizendo é que ao usar o `abntex2cite` o parênteses funciona, *mas usando o estilo saem incorretamente colchetes*:
## `abntex2-num`
![abntex2-num](https://cloud.githubusercontent.com/assets/5324013/7927384/78b03502-08b5-11e5-9b54-1434b37c4e77.png)

## `abntex2cite`
![abntex2cite](https://cloud.githubusercontent.com/assets/5324013/7927366/5172c2f2-08b5-11e5-9f12-f5cea0e2f2a7.png)

O resultado é o mesmo usando `pdflatex`, mas nesse caso estou usando XeLaTeX através do `latexmk`.

A seção 4.1 menciona que usar o estilo `abntex2-num` traz a formatação correta, mas me pareceu um bug receber colchetes ao invés de parênteses. Veja distinção nas imagens acima.

**Comment by kerscher** [comment]
MWE para `pdflatex`:
```latex
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}

\title{Exemplo de citação}
\author{}
\date{}

\begin{document}
\maketitle

\renewcommand{\abstractname}{}
\begin{abstract}
\end{abstract}

Essa é uma citação usando apenas o estilo \texttt{abntex2-num}: \cite{somecitation}.

\renewcommand{\refname}{Bibliografia}
\bibliographystyle{abntex2-num}
\bibliography{/home/youruser/.yourlibrary.bib}

\end{document}
```

![mwe-abntex2-num](https://cloud.githubusercontent.com/assets/5324013/7927515/78ce28b2-08b7-11e5-9641-b7fd4244fe86.png)

**Comment by ycherem** [comment]
Exatamente isso que diz a seção 4.1:

 "\bibliographystyle{abnt-num}
Dessa forma, *as citações no texto seguirão o padrão do Latex*, porém a
bibliografia será
formatada conforme o padrão brasileiro."

Padrão do Latex = colchetes.

Isso independentemente de compilar com latex, pdflatex, xelatex ou lualatex.

Existe algum inconveniente em utilizar \usepackage[num]{abntex2cite}?




Youssef Cherem
________________
!المسيح قام! حقاً قام

2015-06-01 23:32 GMT-03:00 Yghor Kerscher <notifications@github.com>:

**Comment by kerscher** [comment]
Nenhum. Apenas não sabia se os colchetes eram um bug ou não.
Não havia ficado claro que a formatação estava conforme a norma mesmo com os colchetes. Agora sei que não está, mas que faz parte da forma como a citação padrão funciona. Obrigado.
