### ISSUE TITLE
abntex2cite no Lyx renderiza diferentes estilos de bibliografia ao exportar para vários formatos

### ISSUE THREAD

**Issue by virgolino** [abntex/abntex2#156]
Olá, estou tentando iniciar utilizando o estilo de documento abntex2 para elaboração de tese, usando o Lyx, porém encontro inconsistências ao renderizar o documento final. Dependendo do formato de arquivo de exportação escolhido, as referências são formatadas de diferentes formas, por exemplo, se exporto para PDF, o título é transformado todo em lowercase, com a primeira letra maiúscula, porém as siglas também em minúscula (p.ex. HTLV se torna htlv); Se exporto para MS WORD (.doc), o estilo usado se torna citação numérica, todos os autores aparecem com o nome completo, mas o título aparece com case correto.
O meu Lyx foi corretamente configurado como proposto em [https://github.com/abntex/abntex2/wiki/LyX](url), inclusive usando configuração de 'local layout' para correta configuração do natlib;
Como banco de dados bibliográfico, utilizo o JabRef (que já vem incluído como padrão na instalação completa do Lyx);
Como anexo incluo um arquivo .Lyx simples que criei como teste, apenas para testar a renderização das referências, e imagens das diferentes saídas de exportação deste arquivo;
Alguma ideia do que pode estar ocorrendo?

![teste](https://cloud.githubusercontent.com/assets/17225881/13031043/8df5ddd4-d29c-11e5-8255-a5ff1cceba1f.jpg)

[teste.txt](https://github.com/abntex/abntex2/files/129478/teste.txt)

**Comment by ycherem** [comment]
Utilizar conversores para .docx ou .html nunca é uma boa ideia. Você precisa disso?

**Comment by virgolino** [comment]
Oi, pensei nesta solução para os casos em que as regras utilizadas desviem um pouco da abnt, o que é o caso em várias instituições, como onde eu curso mestrado. Alguma outra sugestão?

**Comment by ycherem** [comment]
Desde quando converter para Word é uma solução? Se quer fazer a tese em Word, use Word. Exportar não vai te ajudar em nada, só vai fazer perder tempo. A sugestão é simples: o estilo contempla a ABNT; se a sua instituição não, você pode modificar o estilo, seja o estilo `biblatex-abnt` ou o `abntex2cite`, ou então não usar ferramentas bibliográficas para Latex.
