### ISSUE TITLE
A classe abntex2 não roda o macro `\frontmatter` do memoir

### ISSUE THREAD

**Issue by hugomg** [abntex/abntex2#158]
A minha universidade exige que todos os elementos pré-textuais sejam impressos na folha da frente, nunca no verso. Eu posso chegar perto disso colocando vários \cleardoublepage entre os elementos pré-textuais mas, se um desses elementos  (como o \tableofcontents) ocupar mais de uma página ele vai imprimir no verso, pois não tenho como botar um \cleardoublepage no meio.

Pesquisando na web, achei [esse workaround](http://tex.stackexchange.com/a/118501/45056), que insere um "if" no início de cada página:

    \usepackage{everyshi}
    \makeatletter
    \EveryShipout{\if@mainmatter\else\ifodd\c@page\null\pagebreak\fi\fi}
    \makeathother

O problema é que a variável `@mainmatter` é sempre verdadeira quando uso o abntex2. O `\frontmatter` do memoir setaria essa flag pra falso mas o abntex2 sobrescreve o `\frontmatter` com um `\renewcommand`, fazendo o `@mainmatter` ficar com o  valor padrão, que é verdadeiro.

Eu acho que o abntex2 não deveria "sobrescrever" comportamentos padrão do memoir. Tem como  fazer a nova versão do `\frontmatter` chamar a versão antiga ao invés de só sobrescrevê-la?

BTW, não sei se outras universidades também tem essa exigência de "one-side" nos elementos pré-textuais mas poderia ser uma feature interessante pro abntex2.

**Comment by ycherem** [comment]
v
​eja:​
http://tex.stackexchange.com/questions/28359/changing-oneside-and-twoside-layout






Youssef Cherem
________________
!المسيح قام! حقاً قام

2016-03-10 0:07 GMT-03:00 hugomg <notifications@github.com>:

**Comment by hugomg** [comment]
@ycherem: A solução desse link é o que já estou fazendo (usar cleardoublepage). O problema é que isso depende de que todos os elementos pré-textuais caibam em uma única página. Se a tableofcontents for muito grande não dá certo.

De qualquer forma, não estou perocupado só com o "hack" que estou fazendo para a minha tese :) O memoir usa a variável @mainmatter internamente pra várias coisas e pode ser que o abntex2 esteja interferindo com isso. Também são sei se o abntex2 está sobrescrevendo outros macros que funcional de forma similar ao `\frontmatter`... Resumindo, queria chamar a atenção dos desenvolvedores pra isso.

**Comment by ycherem** [comment]
A solução do link não é usar \cleardoublepage.
Não há \cleardoublepage nisto:

\documentclass[oneside]{abntex2}

\usepackage{geometry}

\usepackage{lipsum}

\newcommand{\teste}{\chapter{Foo}
    \section{title}
    \subsection{Bar}
    \lipsum[1-7]}


\begin{document}

\tableofcontents*

\clearpage
\begin{resumo}[Abstract]
    content...
\end{resumo}

\begin{resumo}
    content...
    \end{resumo}

\textual
\newgeometry{twoside}


\teste
\teste
\teste
\teste
\teste
\teste
\teste
\teste\teste
\teste
\teste
\teste\teste
\teste
\teste
\teste\teste
\teste
\teste
\teste\teste
\teste
\teste
\teste\teste
\teste
\teste
\teste\teste
\teste
\teste
\teste

\end{document}


Note que o sumário passa de uma página a outra etc.

Youssef Cherem
________________
!المسيح قام! حقاً قام

2016-03-10 11:25 GMT-03:00 hugomg <notifications@github.com>:
