### ISSUE TITLE
Uso de \uppercase no título da seção de bibliografia gerando Warning

### ISSUE THREAD

**Issue by lordantonelli** [abntex/abntex2#159]
> Package hyperref Warning: Token not allowed in a PDF string (Unicode): removing `\uppercase' on input line 3.

O erro aparece ao utilizar outros idiomas (inglês, por exemplo).

Sugiro a correção da linha 546 da arquivo abntex2.cls

**Comment by ycherem** [comment]
Não é uma mensagem de erro -- é só um aviso. Mudar essa linha desconfiguraria a seção no sumário.

**Comment by lordantonelli** [comment]
Qual seria o impacto de desconfiguração se substituir a referida linha por esta?

`\addcontentsline{toc}{chapter}{\texorpdfstring{\MakeTextUppercase{\bibname}}{\bibname}}`

**Comment by laurocesar** [comment]
@lordantonelli e @ycherem , essa substituição surgiu alguma alteração do sumário? Se não, parece-me tranquilo fazer a substituição.

**Comment by lordantonelli** [comment]
No meu projeto não houve alterações (tanto nos idiomas brazil, quanto no english)... e a mensagem de warning desapareceu.

**Comment by laurocesar** [comment]
Ok. Implementado. Obrigado pela sugestão, @lordantonelli , e pela análise, @ycherem !

**Comment by jbsilva** [comment]
Faltou fazer o mesmo para a linha 883.
de: \renewcommand{\appendixtocname}{\uppercase{#2}}
para: \renewcommand{\appendixtocname}{\texorpdfstring{\MakeTextUppercase{#2}}{#2}}
