### ISSUE TITLE
Na ficha catalográfica, se o nome da instituição é longo, a margem é ultrapassada

### ISSUE THREAD

**Issue by italovieira** [abntex/abntex2#160]
![2016-03-18-16 07 50](https://cloud.githubusercontent.com/assets/8337230/13889165/d27d35e6-ed23-11e5-9236-2a1a5e30656e.png)

O modelo usado é o de trabalho acadêmico.

P.S.: Não verifiquei para outros dados igualmente longos, se a margem também é ultrapassada.

**Comment by ycherem** [comment]
A fica catalográfica geralmente é feita pela biblioteca de sua instituição:

 \begin{fichacatalografica}
     \includepdf{fig_ficha_catalografica.pdf}
 \end{fichacatalografica}

Como esses comandos estão em um parbox, não haverá quebra de parágrafo.

Se não, use o pacote mdframed e resolva todos os seus problemas:

\begin{fichacatalografica}

	\vspace*{\fill}					% Posição vertical
	\begin{mdframed}[userdefinedwidth=0.8\textwidth,align=center]

\small
\sffamily
\imprimirautor

\noindent \imprimirtitulo  / \imprimirautor. -- \imprimirlocal, \imprimirdata. \pageref{LastPage} p. : il. (algumas color.) ; 30 cm.\\
					
\noindent \imprimirorientadorRotulo~\imprimirorientador\\
					
\noindent \imprimirtipotrabalho~--~Escreva aqui o nome longo de sua instituição, seu instituto, sua faculdade, seu programa etc etc etc.,
					\imprimirdata.
					
\noindent 1. Palavra-chave1.
2. Palavra-chave2.
3. Palavra-chave3.
I. Orientador.
II. Universidade xxx.
III. Faculdade de xxx.
IV. Título 			
	\end{mdframed}
	
\end{fichacatalografica}
