### ISSUE TITLE
Customizações da Escola Politécnica da Universidade de São Paulo (EPUSP)

### ISSUE THREAD

**Issue by maiaftv** [abntex/abntex2#162]
Amigos, fui utilizar o pacote capa-epusp-abntex2.sty e acredito que o mesmo é incompatível com as versões mais novas do abntex2. Basta incluir o pacote no documento que não consigo compilar devido ao erro "There's no line here to end".

O erro aparece logo após o comando \imprimirfolhaderosto:

```
% ---
% Folha de rosto
% (o * indica qrm ue haverá a ficha bibliográfica)
% ---
\imprimirfolhaderosto*
% ---

```

Alguém, por favor, poderia me dar uma luz?

**Comment by ycherem** [comment]
Compilando um exemplo simples com o arquivo `.sty`, não ocorre erro algum. Pode enviar um exemplo mínimo para o fórum abntex2, deve ser algum problema com seu arquivo.

**Comment by maiaftv** [comment]
Olá ycherem. O erro se dá com os modelos canônicos do pacote abntex2,  https://www.ctan.org/pkg/abntex2

**Comment by ycherem** [comment]
Pois é, o modelo _não é um exemplo mínimo_. Tente compilar um doc. simples, como:

```
\documentclass{abntex2}

\usepackage{capa-epusp-abntex2}

% Informações de dados para CAPA e FOLHA DE ROSTO
% ---
\titulo{Modelo Canônico de\\ Trabalho Acadêmico com \abnTeX}
\autor{Equipe \abnTeX}
\local{Brasil}
\data{2016, v<VERSION>}
\orientador{Fulano de Tal}
\coorientador{Beltrano de Tal}
\instituicao{%
	Universidade Federal de Viçosa
	\par
	Faculdade de Agronomia
	\par
	Programa de Pós-Graduação}
	\tipotrabalho{Tese (Doutorado)}
	% O preambulo deve conter o tipo do trabalho, o objetivo, 
	% o nome da instituição e a área de concentração 
	\preambulo{Modelo canônico de trabalho monográfico acadêmico em conformidade com
		as normas ABNT apresentado à comunidade de usuários \LaTeX.}

\areaconcentracao{Engenharia Elétrica - Sistemas Eletrônicos}

\begin{document}
\imprimircapa

\imprimirfolhaderosto


\end{document}
```
Você vai ver que não há erros.

**Comment by maiaftv** [comment]
Discordo do fechamento da issue. Se não funciona com o modelo canônico da suíte abntex2, qual a serventia? Não acho que sua abordagem esteja sendo positiva, ycherem. Me parece estar fugindo do problema.

**Comment by ycherem** [comment]
@maiaftv, acabei de compilar novamente com o modelo canônico e **não houve um erro sequer**. Simplesmente acrescentei 

```
\usepackage{capa-epusp-abntex2}
\areaconcentracao{Engenharia Elétrica - Sistemas Eletrônicos}
```
Em suma, o "problema" não existe. A não ser que dê outras informações (versão Latex etc.), é impossível descobrir o teu problema.

**Comment by maiaftv** [comment]
@ycherem, o problema ocorre quando não se coloca a área de concentração. Como é obrigatório incluir na minha universidade, está resolvido o problema! Obrigado.

**Comment by ycherem** [comment]
@maiaftv, que bom que deu certo. 

> Não acho que sua abordagem esteja sendo positiva, ycherem. Me parece estar fugindo do problema.

Todas as pessoas que atuam no projeto `abntex` dedicam seu tempo livre para ajudar os outros. No mínimo, se você tivesse feito um pequeno teste, resolveria seu problema sozinho; ou se enviasse um exemplo do seu problema, obteria uma resposta mais rápida para suas dúvidas. Então, antes de criticar, deveria considerar se sua atitude precipitada e rude está sendo condizente com um ambiente coletivo cuja intenção é proporcionar uma solução para problemas que, individualmente, nós próprios não temos. Portanto, modere seu linguajar antes de acusar alguém que faz um trabalho voluntário de estar "fugindo do problema". 

Em todo caso, sinta-se bem-vindo para fazer sugestões ou contribuições ao projeto, e quem sabe também ajudar outras pessoas. 

> **Happy TeXing!**

**Comment by maiaftv** [comment]
@ycherem, entendo o seu ponto de vista e lamento a aparente rudeza. Não foi minha intenção. Continuo não concordando, no entanto, com o fechamento sumário do problema por você, afinal o mesmo ainda existia.

> Compilando um exemplo simples com o arquivo .sty, não ocorre erro algum. Pode enviar um exemplo mínimo para o fórum abntex2, deve ser algum problema com seu arquivo.

Receber esta resposta após meu primeiro tópico aberto aqui e o mesmo ser fechado ainda que o problema estivesse ocorrendo não me parece a abordagem de alguém que esteja querendo resolver.

Como trabalho voluntário e com dedicação de tempo livre, entendo que é melhor não atrapalharmos se não quisermos ajudar.

> **Happy TeXing for you, too!**
