### ISSUE TITLE
Não imprime informações extras da edição da bibliografia (norma 6023:2002)

### ISSUE THREAD

**Issue by paulochf** [abntex/abntex2#165]
Oi gente!

Estou ajudando minha noiva a escrever um trabalho da pós em Direito dela. O problema é que ela precisa fazer a referência da seguinte forma:

![image](https://cloud.githubusercontent.com/assets/107470/16937936/89022c42-4d49-11e6-8993-413250d8325d.png)

Aí eu tento fazer isso no .bib

```
@book{berenice,
	Address = {São Paulo},
	Author = {Maria Berenice Dias},
	edition = {11 ed. rev., atual. e ampl.},
	Publisher = {Editora Revista dos Tribunais},
	Title = {Manual de direito das famílias},
	Subtitle = {de acordo com o novo {CPC}},
	Year = {2016}}
```

e sai

![image](https://cloud.githubusercontent.com/assets/107470/16937955/bca2f180-4d49-11e6-94dd-f0f3d6570faa.png)

(aparecem 2 'ed', um no fim da informação)

Acho isso um meio-bug/meio-feature, já que isso faz parte da norma [6023:2002](http://www.usjt.br/arq.urb/arquivos/abntnbr6023.pdf), item 8.3.1 sobre "Edição"

> 8.3.1 Indicam-se emendas e acréscimos à edição, de forma abreviada.
Exemplo: FRANÇA, Júnia Lessa et al. **Manual para normalização de
publicações técnico-científicas**. 3. ed. rev. e aum. Belo Horizonte:
Ed. da UFMG, 1996.

Eu sou meio leigo na "programação" LaTeX, então só hoje descobri a função do tipo de arquivo .bst (e a sua sintaxe doida, que eu pensei em aprender mas não acho que consigo fazê-lo até esta 6a feira, data da entrega do trabalho). Minha idéia era estender o algoritmo da info de edição da referência para que, se o valor atribuído na entrada do .bib não fosse um número, ou seja,

`edition = {11 ed. rev., atual. e ampl.},`

ele colasse esse texto sem alterações.

Fica a sugestão, com um pedido de ajuda implícito. :pray:

Valeu!

**Comment by danielbmarques** [comment]
Não sei se você tem tempo e/ou interesse, mas o [`biblatex-abnt`](https://github.com/abntex/biblatex-abnt) já faz isso.

**Comment by danielbmarques** [comment]
PS: O exemplo da norma que você citou está no manual do `abntex2cite` com esta sintaxe: `edition={{3}. ed. rev. e aum.}`.
Como eu não uso o `abntex2cite`, não sei se funcionaria, mas tenta colocar o número entre chaves e vê se resolve. Vale a tentativa.

**Comment by paulochf** [comment]
@danielbmarques, isso resolve! Muito obrigado!

Agora achei a referência no manual (pág 63). Percebi que o CTRL F do meu evince me enganou.
