### ISSUE TITLE
Referências com omissão de mesmo autor/título só faz sentido sem interligação com entrada na bibliografia

### ISSUE THREAD

**Issue by paulochf** [abntex/abntex2#167]
Na bibliografia faz sentido ocorrer o seguinte:

![image](https://cloud.githubusercontent.com/assets/107470/19025337/f9c81722-88ed-11e6-8312-798484652d54.png)

mas não no rodapé

![image](https://cloud.githubusercontent.com/assets/107470/19025357/20f6faca-88ee-11e6-8758-1187dac2f30f.png)

Acho que a avaliação da referência ser repetida (ou não) deveria ocorrer somente no ponto onde vai ser renderizada, não?

**Comment by dbmrq** [comment]
Só pra avisar, isso já está resolvido no [`biblatex-abnt`](https://github.com/abntex/biblatex-abnt).

Como eu menciono [no manual](https://github.com/abntex/biblatex-abnt/blob/master/doc/biblatex-abnt.pdf), ele usa automaticamente a referência resumida ou as abreviações "id.", "ibid." e "op. cit" de acordo com a norma da ABNT:

![abnt-ibid](https://cloud.githubusercontent.com/assets/15813674/19030922/4ab74df4-8927-11e6-8c2b-81434918ca5a.png)

**Comment by paulochf** [comment]
Legal, @dbmrq! Obrigado pela indicação!

Eu até tentei usar o biblatex-abnt. Instalei o texlive-bibtex-extras mas ele ainda tava sentindo falta de algo. Talvez você possa me ajudar nisso... :)

Pergunta de curioso: abnt2cite vai ser deprecado em favor do biblatex-abnt em algum momento?

**Comment by dbmrq** [comment]
Pelo jeito você está usando algum gerenciador de pacotes de um sistema operacional, né. Nas minhas poucas experiências com Linux isso me deu várias dores de cabeça, acho que o mais fácil é desinstalar a sua versão e instalar a versão vanilla seguindo as instruções do [site](https://www.tug.org/texlive/quickinstall.html).

Dê uma olhada também [aqui](http://tex.stackexchange.com/q/200209/102699), [aqui](http://tex.stackexchange.com/a/95373/102699) e [aqui](https://ubuntuforums.org/showthread.php?t=2130068).

Se você quiser ficar com a versão do seu gerenciador de pacotes, vai ter que descobrir na marra qual é o problema. Muitas versões nem vêm com o `tlmgr`, você vai ter que fazer umas gambiarras ([isso?](http://askubuntu.com/q/485514), [isso?](http://tex.stackexchange.com/a/171560/102699), não sei, rs.). O BibLaTeX vira e mexe se enrola com os diretórios e permissões diferentes. Talvez você também tenha que [mudar algo](http://tex.stackexchange.com/q/102817/102699) pra rodar o Biber no seu arquivo.

Se você tiver mais alguma dúvida abra uma issue [lá no repositório](https://github.com/abntex/biblatex-abnt) pra não sequestrarmos esta aqui.

E a intenção é que o [abntex3](https://github.com/abntex/abntex3) use o BibLaTeX. Acho que só falta adaptar os modelos do abntex2.

**Comment by ycherem** [comment]
@dbmrq , estou mexendo nesses modelos [aqui](https://github.com/ycherem/abntex3).

**Comment by paulochf** [comment]
Puxa, muito obrigado mesmo @dbmrq pelas instruções completas!

Como o prazo de entrega do meu trabalho é de dias, testarei depois disso.

> Se você tiver mais alguma dúvida abra uma issue lá no repositório pra não sequestrarmos esta aqui.

Pode deixar! Se for algo mais leve do que um possível bug, postarei no grupo do LaTeX-BR/ABNTex2.

> E a intenção é que o abntex3 use o BibLaTeX. Acho que só falta adaptar os modelos do abntex2.

Beleza! Se a migração já está ocorrendo e no biblatex já está corrigido, tentarei usá-lo. Só não sei o que fazer com esta issue então (fecha ou não?).

Abs!

**Comment by dbmrq** [comment]
@ycherem Ah, legal! Vou olhar quando tiver um tempo. Por que você já não coloca direto no repositório do abntex mesmo, não é mais fácil?

Também seria uma boa fazer uma issue com uma checklist de tudo o que precisa ser feito, talvez até uma checklist pra cada modelo/manual, tipo assim:

* Modelo 1:
    - [ ] Corrigir isso
    - [ ] Acrescentar aquilo

Aí a gente pode ir fazendo aos poucos e um complementando o trabalho do outro sem se perder no que já foi feito ou não.

**Comment by ycherem** [comment]
@dbmrq <https://github.com/dbmrq> , Eu queria que alguém desse uma olhada
para ver como está ficando, antes de colocar no repositório. Seria bom uma
checklist, nem sei o que falta (as mudanças não eram muitas).

Youssef Cherem



2016-10-03 17:04 GMT-03:00 Daniel Marques <notifications@github.com>:

**Comment by dbmrq** [comment]
@paulochf Só note que o sistema de citação nas notas de rodapé por enquanto só está disponível aqui no GitHub, não no TeX Live, então você vai ter que copiar os arquivos manualmente. Mas é fácil (ao menos com o TeX Live vanilla). Vou usar a versão nova por um tempo e se parecer que está tudo certo envio para o ctan.

**Comment by paulochf** [comment]
Tranquilo, @dbmrq! Não tenho problemas em usar vrsões de dev :)
Só espero não tomar susto com outro problema hehe!

**Comment by dbmrq** [comment]
@ycherem Entendi. Parece estar ficando bom. Dei uma olhada no `abntex3.pdf` e só tem um ou outro detalhe que falta arrumar, tipo as seções 2.3 e 2.4. E daí tem que mudar os modelos também, né.

Eu nunca nem usei a classe `abntex2`, só usava o `abntex2cite` isoladamente, então também não tenho muita ideia do que precisa mudar, por isso não me aventurei a tentar, fiquei meio perdido com o monte de arquivos.

Inclusive acho que é uma boa os projetos serem mais ou menos independentes e terem cada um seu próprio manual, só apontando as relações quando for relevante. Pra mim já está mais do que bom como está. Acho que nem precisariam ser incluídos diretamente os arquivos do `biblatex-abnt`, é melhor uma abordagem mais modular, tem menos lugares pra atualizar e menos coisas pra dar errado. E mesmo pros usuários acho que seria menos intimidante do que abrir a pasta `doc` e encontrar um milhão de arquivos.
