### ISSUE TITLE
Chave pública do repositório debian não está mais disponível

### ISSUE THREAD

**Issue by dpasqualin** [abntex/abntex2#168]
Seguindo os passos do [guia de instalação](https://github.com/abntex/abntex2/wiki/InstalacaoLinux), notei que a chave pública não está mais disponível no caminho mencionado: http://distrib.abntex2.googlecode.com/hg/debian/89C55467.asc

**Comment by ycherem** [comment]
Você precisa instalar desse jeito? É sempre mais complicado, e as
atualizações demoram para aparecer (se é que aparecem).

Youssef Cherem



2016-10-03 11:36 GMT-03:00 Diego Giovane Pasqualin <notifications@github.com

**Comment by dpasqualin** [comment]
@ycherem , o pacote texlive-publishers possui a versão mais nova do abntex2 nas distribuições mais recentes (debian 8, ubuntu 16..) ?

**Comment by edusantana** [comment]
@dpasqualin Eu utilizo o ubuntu 16.04 e o abntex2 funciona. Mas não é a última versão. Você pode ver as versões [a partir dessa página](http://packages.ubuntu.com/search?keywords=texlive).

Por exemplo, [o xenial](http://packages.ubuntu.com/xenial/texlive) utiliza a versão `2015.20160320-1`. Enquanto [yakkety](http://packages.ubuntu.com/yakkety/texlive) utiliza `2016.20160819-2`.

Se você quiser utilizar a partir da última versão publicada, recomendo instalar a partir do tug.

Para uma instalação "mínima":
```
wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz 
tar -xf install-tl-unx.tar.gz && cd install-tl-* 
wget https://raw.githubusercontent.com/abntex/limarka/master/spec/dependencias/texlive-abntex2.profile
sudo ./install-tl -no-gui -profile texlive-abntex2.profile 
```

Depois tem que adicionar a instalação ao PATH, ler a mensagem no final da instalação para ver como proceder.
