### ISSUE TITLE
Citação com notas de rodapé

### ISSUE THREAD

**Issue by Fer22f** [abntex/abntex2#169]
Seria possível eu fazer um modelo com notas de rodapé junto com o estilo num do bibtex? Seria basicamente ter um rodapé com o \citetext.

Eu preciso disso pra fazer um modelo da PUC-PR, e não tenho experiência com o LaTeX, só sei usar alguns comandos. Por exemplo vi que o bibtex tem o \footcite mas não acho que está disponível.

**Comment by ycherem** [comment]
Use

*biblatex:*\documentclass{article}


\usepackage[brazil]{babel}

\usepackage[
backend=biber,
style=abnt-numeric,
sorting=none,
bftitles,
indent,
]{biblatex}
\addbibresource{\jobname.bib} % if you’re using biblatex
\usepackage{filecontents}

\begin{filecontents*}{\jobname.bib}
  @book{Knu86,
    author = {Knuth, Donald E.},
    year = {1986},
    title = {The \TeX book},
  }

    @book{Knu00,
        author = {Knuth, Donald E. and Fulano da Silva},
        year = {1986},
        title = {The \TeX book},
    }

\end{filecontents*}




\DeclareCiteCommand{\footcite}[\mkbibfootnote]
{\usebibmacro{prenote}}
{\usebibmacro{citeindex}%
    \usebibmacro{cite}}
{\multicitedelim}
{\usebibmacro{postnote}}

\begin{document}

\footfullcite{Knu86}.

\footfullcite{Knu00}.



\printbibliography
\end{document}


===

Só lembrando: segundo a ABNT, você não pode usar o estilo numérico e notas
de rodapé no mesmo documento.


Ou acho que dá para criar um comando assim:

\newcommand{\cita}[1]{\citetext{#1} }


Youssef Cherem



2016-10-21 7:34 GMT-02:00 Fer22f <notifications@github.com>:
