### ISSUE TITLE
Link de referencia com <> no código.

### ISSUE THREAD

**Issue by xR2** [abntex/abntex2#172]
Vou jogar o print e logo de cara se percebe o problema:

![task2](https://cloud.githubusercontent.com/assets/17341234/21609133/679d6c12-d19f-11e6-9319-8b2f9cb69ab3.png)

Link correto: `http://www.osti.gov/scitech/biblio/1333703`
Link gerado: `<http://www.osti.gov/scitech/biblio/1333703>`

```
\documentclass[a4paper]{memoir}
\usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
\usepackage[utf8]{inputenc}		% Codificacao do documento (conv. auto. dos acentos)
\usepackage[brazil]{babel}
\usepackage{hyperref}
\usepackage[backend=biber,style=abnt-numeric,language=brazilian,alldates=long,sorting=none,hyperref,maxcitenames=2,maxbibnames=99,citecounter=true]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{referencias.bib}
@TechReport{OWL,
  author      = {David Sassani and Je-Hun Jang and Paul Mariner and Laura L. Price and Robert P. Rechard and Mark J. Rigali and Ralph Rogers and Emily Stein and Walter M. Walkow and Philippe F Weck},
  title       = {The On-line Waste Library ({OWL}): Usage and Inventory Status Report.},
  institution = {Sandia National Laboratories},
  year        = {2016},
  month       = sep,
  doi         = {10.2172/1333703},
  url         = {http://www.osti.gov/scitech/biblio/1333703},
  urldate     = {2016-12-06},
  groups      = {Rejeito},
  publisher   = {Office of Scientific and Technical Information ({OSTI})},
}
\end{filecontents}
\addbibresource[]{referencias.bib}

\begin{document}
Blablabla \cite{OWL}
\printbibliography
\end{document}

```

**Comment by dbmrq** [comment]
@xR2 Esse problema já está resolvido no branch `master`. Veja [aqui](https://github.com/abntex/biblatex-abnt/issues/16) e [aqui](https://github.com/abntex/biblatex-abnt/commit/ba9349dc5a2d7047626baa7ce481a4d432d2b455). Essa versão ainda não está no ctan, mas se você instalar o `biblatex-abnt` manualmente aqui do GitHub deve estar tudo certo.

**Comment by gusbemacbe** [comment]
I copied the codes from @xR2 here and from https://github.com/abntex/biblatex-abnt/issues/5. But it did not work yet. 

You can get my full file and analyse:

[Meu trabalho](https://github.com/abntex/abntex2/files/2591526/3.Trabalho.zip)

**Comment by dbmrq** [comment]
Eu só vou conseguir olhar isso segunda-feira. Enquanto isso, tente criar um exemplo mínimo. Isso vai te ajudar a resolver o problema e, se você não conseguir, vai facilitar pra que eu te ajude também. Alguns links:

https://tex.meta.stackexchange.com/a/3225/102699
https://texfaq.org/FAQ-minxampl
http://minimalbeispiel.de/mini-en.html

**Comment by gusbemacbe** [comment]
Olá!

Vou simplificar minhas explanações e minimizar bastante o código-fonte para separar os trechos.

* Eu utilizo Biblatex (`biber 2.12`), XeLaTeX (`XeteX 3.1415`) e as últimas versões dos pacotes `abntex2` e `biblatx-abntex2` no macOS High Sierra 10.13.6.
* Esses pacotes foram instalados do TeX Live Utility por meio d MacTeX instalado via Homebrew.
* Eu também uso o Linux, mas não testei aquele problema no Linux.

Nesta imagem acima, tu podes observar os `< >` onde as ligações (*links*, URLs) não estão lá ou desapareceram.

Aqui estão pequenos e mínimos trechos separados de códigos (tu podes pegar meu ficheiro zipado completo acima):

* Eu adicionei o primeiro comando recursivo e customizei o documento, utilizando ` abntex2`:

```latex
    % !TeX program = xelatex
    \documentclass[10pt, a4paper, brazil]{abntex2}
```

* Adicionei alguns pacotes importantes para a bibliografia funcionar, utilizando e aplicando `abnt` para o estilo da bibliografia. Também observa que acrescentei `hyperref` ao pacote `biblatex` e aderi `\usepackage{hyperref}` para `\hypersetup`

```latex
    \usepackage[alf]{abntex2cite}
    \usepackage[autostyle]{csquotes}
    \usepackage[backend = biber, alldates=long, hyperref, justify, language = brazil, scbib, sorting = none, style = abnt, url = true]{biblatex}
    \usepackage[brazil]{babel}
    \usepackage[T1]{fontenc}
    \usepackage[utf8]{inputenc}
    \usepackage{filecontents}
    \usepackage{polyglossia}
```

* Com o pacote `filecontents`, eu aderi o comando para gerar o novo ficheiro .bib para executar `biber`. Ei-lo:

```latex
    \addbibresource{referencias.bib}
    
    \begin{filecontents}{referencias.bib}
    @online{google,
        doi             = {docs},
        organization    = {Google},
        title           = {Documentação do Google Cloud SDK},
        url             = {https://cloud.google.com/sdk/docs},
        urldate         = {2018-10-26}
    }
    \end{filecontents}
```

* Iniciando o documento, sem me esquecer de acrescentar alguns comandos como `textual`, `bookmarksetup` e `postextual`  e de seleccionar o idioma:

```latex
    \begin{document}
    \selectlanguage{brazil}

    \textual

    % ...
    
    \citetitle{google}

    \bookmarksetup{startatroot}% 
    \postextual
    
    \printbibliography
    
    \end{document}
```

* Se quiseres ver como fica o `hypersetup` para teres certeza que ele também deve causar problemas, e observa que acrescentei `makeatletter` e alguns comandospara `hypersetup`. Dentro dele, adicionei alguns comandos para tentar fazer com que a bibliografia funcionasse:

```latex
\makeatletter
\hypersetup{
    bookmarksdepth=4,
    bookmarks=true,                                      % mostrar a barra de favoritos
    citecolor=riverbedblue2,                             % cor das lgações para bibliografia
    colorlinks=true,                                     % false: logações em caixa; true: logações coloridas
    filecolor=magenta,                                   % cor das ligações dos ficheiros
    linkcolor=contessa,                                  % cor dos links internos (mudança da cor da caixa com linkbordercolor)
    pdfauthor={Gustavo Costa},                           % autor do documento
    pdfcreator={Criado com CLI do XeLaTeX e Biblatex},   % creator of the document
    pdffitwindow=true,                                   % janela ajustada à página quando aberta
    pdfkeywords={Docker, Google, Google Cloud Platform, 
                 WordPress},                             % lista de palavras-chave
    pdfmenubar=true,                                     % mostrrar o menu do Acrobat?
    pdfnewwindow=true,                                   % ligação na nova janela do PDF
    pdfpagemode=FullScreen,                              % Mostrar o ecrNa cheio
    pdfproducer={Visual Studio Code Insiders},           % produtor do documento
    pdfstartview={FitH},                                 % cabe a largura da página para a janela
    pdfsubject={Configurar o Google Cloud Platform
                dentro do Docker e instalar o WordPress
                dentro do Google Cloud Platform},        % assunto do documento
    pdftitle={Docker com Wordpress Cluster 
              e Google Cloud},                           % título
    pdftoolbar=true,                                     % mostrar barra de marcadores do Acrobat
    unicode=true,                                        % caracteres não latinos nos marcadores do Acrobat
    urlcolor=horizon,                                    % cor das ligações externas
    pdfinfo=
    {
      CreationDate={20181112212635},                   % data de criação
      ModDate={20181112212635}                         % data de modificação
    }
}
\makeatother
\makeindex
\setlrmarginsandblock{3cm}{3cm}{*}
\setulmarginsandblock{3cm}{3cm}{*}
\checkandfixthelayout
\setlength{\parindent}{1.3cm}
\setlength{\parskip}{0.2cm}
\SingleSpacing
```

* Executei os comandos no terminal assim:

```bash
    xelatex -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape relatório
    biber relatorio
    xelatex -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape relatório
    xelatex -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape relatório
```

* Também fiz um teste mínimo de códigos tomados do @xR2, só que troquei `article` pelo `abntex2` e as ligações na bibliografia funcionaram. Não sei por que as na minha bibliografia não funcionaram. Deve ser por causa de alguns certos pacotes, ou do `hyperref`, ou de configurações erradas do pacote `biblatex` ou do `hypersetup` ou até do `documentclass`.
