### ISSUE TITLE
Incompatibilidade com ufsc-thesis

### ISSUE THREAD

**Issue by xR2** [abntex/abntex2#173]
Bom dia, espero que este não seja mais uma _issue_ repetido... kkkk.

Logo que atualizei o abntex2, para esta versão de 29 de novembro, não consigo mais compilar.

`Missing number, treated as zero. \RequirePackage`

A linha apotada com o erro seria 27 do ufsc-thesis.cls

```
% Carrega como base a classe 'abntex2'
\LoadClass[%
  twoside, % Impressão nos dois lados da folha
  chapter=TITLE, % Título de capítulos em caixa alta
  section=TITLE  % Título de seções em caixa alta
]{abntex2}
%
% Manipulação de Strings
\RequirePackage{xstring}
```

Pelo que vi a unica mudança na classe abntex2 foi
`  \addcontentsline{toc}{chapter}{\uppercase{\bibname}}`
para
`  \addcontentsline{toc}{chapter}{\texorpdfstring{\MakeTextUppercase{\bibname}}{\bibname}}`

Talvez seja outra coisa completamente diferente, não sei.
Também postei no hub do ufsc-thesis, mas suspeito que a classe  não esta sendo mantida pois ultima atualização foi ha muito tempo.

**Comment by ycherem** [comment]
Compilei um exemplo mínimo e não ocorreu nenhum erro.
Envie um exemplo mínimo compilável que esteja ocasionando o erro.

Youssef Cherem



2017-01-05 9:04 GMT-02:00 xR2 <notifications@github.com>:

**Comment by xR2** [comment]
Talvez eu esteja com algum arquivo antigo, ou do abntex2 ou do ufsc-thesis, mas conferi tudo anteontem.

```
\documentclass[a4paper]{ufsc-thesis}
\usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
\usepackage[utf8]{inputenc}		% Codificacao do documento (conv. auto. dos acentos)
\usepackage{hyperref}
\usepackage[backend=biber,style=abnt-numeric,language=brazilian,alldates=long,sorting=none,hyperref,maxcitenames=2,maxbibnames=99,citecounter=true]{biblatex}
\usepackage{filecontents}
\usepackage{titlesec}

\begin{filecontents}{referencias.bib}
@TechReport{OWL,
  author      = {David Sassani and Je-Hun Jang and Paul Mariner and Laura L. Price and Robert P. Rechard and Mark J. Rigali and Ralph Rogers and Emily Stein and Walter M. Walkow and Philippe F Weck},
  title       = {The On-line Waste Library ({OWL}): Usage and Inventory Status Report.},
  institution = {Sandia National Laboratories},
  year        = {2016},
  month       = sep,
  doi         = {10.2172/1333703},
  url         = {http://www.osti.gov/scitech/biblio/1333703},
  urldate     = {2016-12-06},
  groups      = {Rejeito},
  publisher   = {Office of Scientific and Technical Information ({OSTI})},
}
\end{filecontents}
\addbibresource[]{referencias.bib}


\begin{document}

\chapter{seila}

Blablabla \cite{OWL}
\printbibliography
\end{document}
```

**Comment by ycherem** [comment]
Seu arquivo compila normalmente, sem erros.

**Comment by xR2** [comment]
Por mais estranho que pareça, quando eu substitui a linha 26 do arquivo novo pelo antigo, passou a funcionar...

```
\ProvidesClass{abntex2}[2016/02/26 v-1.9.6 abnTeX2]
%\ProvidesClass{abntex2}[<CURRENT_DATE> v<VERSION> abnTeX2]
```

Penso que `<VERSION>` era pra ser a versão mesmo, e pelo modo como eu "instalei" ele não conseguiu ler.

**Comment by edusantana** [comment]
Que bom que funcinou @xR2 

Acho que esses valores são substituídos durante a geração da versão.

**Comment by laurocesar** [comment]
@xR2 e @edusantana, o código fonte que está no repositorio precisa ser buildado para deploy. O build irá substituir o <VERSION> pela versão final. Vejam o arquivo build.sh. Há também uma página na Wiki explicando isso.
