### ISSUE TITLE
Inclusão de ISSUE_TEMPLATE.md e CONTRIBUTING.md

### ISSUE THREAD

**Issue by edusantana** [abntex/abntex2#174]
Acho que o projeto se beneficiaria com a criação de um [ISSUE_TEMPLATE](https://help.github.com/articles/creating-an-issue-template-for-your-repository) e CONTRIBUTING.md.

Quando um usuário for criar um novo issue, o github apresenta um link para o texto de `CONTRIBUTING.md`, e o issue é preenchido com o conteúdo do arquivo `ISSUE_TEMPLATE.md`.

Para verificar o comportamento do que estou falando, basta [clicar para criar um novo issue no limarka](https://github.com/abntex/limarka/issues/new).

Acho que poderíamos incluir:

CONTRIBUTING.md

```
- Explicar o que é um exemplo mínimo. Quando um usuário criar um exemplo que não for mínimo nós enviamos esse link para ele.
- Explicar que eles devem facilitar nossa reprodução do erro. Por exemplo: fornecer links para baixar os arquivos necessários para reprodução, etc.
- Explicar que issues que não representam erros serão fechados.
```

ISSUE_TEMPLATE.md:

```
### Sistema utilizado
Sistema: 
Versão do abntex:

### Exemplo mínimo

### Agilizando a reprodução do ambiente mínimo

### Comportamento esperado

### Comportamento atual

```

**Comment by laurocesar** [comment]
Concordo, @edusantana. Você poderia criar?

**Comment by edusantana** [comment]
Oi @abntex/developers gerei os arquivos contendo proposta dos conteúdos. Sinta-se a vontade para editar e melhorá-los.

Você podem inclusive utilizar links, por exemplo: [Fechando o issue](https://github.com/abntex/abntex2/blob/master/CONTRIBUTING.md#fechamento-dos-issues)
