### ISSUE TITLE
Incluir o ambiente quadro no modelo de trabalhos academicos

### ISSUE THREAD

**Issue by edusantana** [abntex/abntex2#176]
- [no fórum](https://groups.google.com/d/msg/abntex2/Hrsix_ArbDA/n2F5tdSiCAAJ)
- https://github.com/abntex/abntex2/issues/83
- https://github.com/abntex/abntex2/issues/166
- https://github.com/abntex/abntex2/wiki/HowToCriarNovoAmbienteListing
- http://tex.stackexchange.com/questions/23078/how-can-i-automatically-center-an-image
- [utilizando trivfloat](https://groups.google.com/forum/#!searchin/latex-br/quadro|sort:relevance/latex-br/WaNYlDRLC7Y/98pqSY8NpXIJ)

**Comment by edusantana** [comment]
Precisei adicionar uma linha com padrão de posicionamento para evitar problemas:

- https://gist.github.com/edusantana/93cfd6855921433fa87be1c791bf4eaa#file-quadro-abntex2-corrigido-tex-L51
- https://groups.google.com/forum/#!topic/latex-br/OhR-54WNEbU

**Comment by laurocesar** [comment]
@edusantana , perfeito, incluído na versão 1.9.7 dos modelos do abntex2
