### ISSUE TITLE
Inserindo lista de código com minted

### ISSUE THREAD

**Issue by luylucas10** [abntex/abntex2#178]
Bom galera. 
Tentei utilizar esse [HowTo](https://github.com/abntex/abntex2/wiki/HowToFormatarCodigoFonte) mas eu utilizo o pacote minted (achei mais interessante e menos trabalhoso de usar, em comparação com o listings) para adicionar os códigos-fonte no meu trabalho.
Tentei fazer algumas alterações como:

```
% Altera o nome padrão do rótulo usado no comando \autoref{}
\renewcommand{\listingscaption}{Código}

% Altera o rótulo a ser usando no elemento pré-textual "Lista de código"
\renewcommand{\listoflistingscaption}{Lista de códigos}

% Configura a "Lista de Códigos'' conforme as regras da ABNT (para abnTeX2)
\begingroup\makeatletter
\let\newcounter\@gobble\let\setcounter\@gobbletwo
  \globaldefs\@ne \let\c@loldepth\@ne
  \newlistof{listings}{lol}{\listoflistingscaption}
  \newlistentry{listing}{lol}{0}
\endgroup

\renewcommand{\cftlistingaftersnum}{\hfill--\hfill}

\let\oldlistoflistings\listoflistings
\renewcommand{\listoflistings}{
   \begingroup
   \let\oldnumberline\numberline
   \renewcommand{\numberline}{\listingscaption\space\oldnumberline}
   \oldlistoflistings
   \endgroup}
```

Eu chamo a lista no documento dessa forma, igual o exemplo

```
% ---
% inserir lista de listings
% ---
\pdfbookmark[0]{\listoflistingscaption}{lol}
\begin{KeepFromToc}
\listoflistings
\end{KeepFromToc}
\cleardoublepage
% ---

```

Porém, sem sucesso. A lista default que o abntex tem é essa abaixo:
![image](https://cloud.githubusercontent.com/assets/8258120/24341415/81bb2b56-1287-11e7-9eda-2e3c842f8449.png)

A que tentei fazer alterando o código fica assim:
![image](https://cloud.githubusercontent.com/assets/8258120/24341441/a4b39f4e-1287-11e7-98d9-8eb460b8ed00.png)

Como se pode ver, não está feio, está horrível e eu não sou muito experiente com latex.
Como faço para que a minha lista de código fique igual a defaul do abntex utilizando o minted?
Obs.: o pacote minted oferece o listing.

Vlw!

**Comment by luylucas10** [comment]
O código que utilizo para adicionar é esse

```
\begin{listing}[H]
\begin{minted}[bgcolor=bg, breaklines=true, frame=single, linenos, numbers=left, breaklines]{xml}
<ContentPage 
  xmlns="http://xamarin.com/schemas/2014/forms"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
  xmlns:sys="clr-namespace:System;assembly=mscorlib" 
  xmlns:toolkit= "clr-namespace:Xamarin.FormsBook.Toolkit;
  		assembly=Xamarin.FormsBook.Toolkit"
  x:Class="MvvmClock.MvvmClockPage"> 
  <StackLayout VerticalOptions="Center">
    <StackLayout.BindingContext> 
      <Binding Path="DateTime"> 
        <Binding.Source> 
          <toolkit:DateTimeViewModel /> 
        </Binding.Source> 
      </Binding> 
    </StackLayout.BindingContext> 
    <Label Text="{Binding Source={x:Static sys:DateTime.Now}, StringFormat='This program started at {0:F}'}" />
    <Label Text="But now..." /> 
    <Label Text="{Binding Hour, StringFormat='The hour is {0}'}" /> 
    <Label Text="{Binding Minute, StringFormat='The minute is {0}'}" /> 
    <Label Text="{Binding Second, StringFormat='The seconds are {0}'}" /> 
    <Label Text="{Binding Millisecond, StringFormat='The milliseconds are {0}'}" /> 
  </StackLayout>
</ContentPage>
\end{minted}
\caption{Código da \textit{View} da aplicação exemplo do livro. Algumas linhas foram quebradas por serem longas. Fonte: \cite{petzold2016}. \label{cod:xaml}}
\end{listing}
```

e fica assim:

![image](https://cloud.githubusercontent.com/assets/8258120/24357376/7fba0f86-12cb-11e7-8acb-c1c722351166.png)

Por isso eu quero utilizar o minted. Tanto xml quando C# ficam estilizados já.

**Comment by edusantana** [comment]
Como você não forneceu um arquivo que possamos tentar, tenta algo +- assim:

```
\begin{listing}[H]
\caption{Código da \textit{View} da aplicação exemplo do livro\label{cod:xaml}}
\begin{minted}[bgcolor=bg, breaklines=true, frame=single, linenos, numbers=left, breaklines]{xml}
<ContentPage 
...
</ContentPage>
\end{minted}
\caption*{Nota: Algumas linhas foram quebradas por serem longas.}
\caption*{Fonte: \cite{petzold2016}. \label{cod:xaml}}
\end{listing}
```

Não testei, mas acho que é isso que você deveria fazer.

Primeiro caption: Título (em cima)
Primeiro caption*: Nota adicional (em baixo, o `*` é para não aparecer a numeração)
Segundo caption*: A Fonte.

Dessa forma, teoricamente, só iria aparecer o título (o primeiro caption) na lista.

O local ideal para voc6e obter esse tipo de suporte é em https://groups.google.com/forum/#!forum/latex-br (tem mais usuários), o github/issue track é para o desenvolvimento do abntex.

**Comment by edusantana** [comment]
@luylucas10 Eu prefiro utilizar o gist para tirar dúvidas. [Veja um exemplo nessa postagem no fórum](https://groups.google.com/forum/#!topic/latex-br/J5JiHmh8x1Q). Perceba que no gist eu forneci um make e um arquivo mínimo, para os que desejarem me auxiliar poderiam fazê-lo com mais facilidade.

**Comment by luylucas10** [comment]
Bom, tentei utilizar como você descreveu, mas ainda não deu certo. o mais próximo que consegui foi isso:

![image](https://cloud.githubusercontent.com/assets/8258120/24384540/8e18ef9a-1332-11e7-98c9-2aee464d7779.png)

Como eu faria para formatar essa lista? A legenda do código ficou OK, porém agora eu preciso formatar essa lista para ficar como as outras. Tem ideia de como fazer?

Obrigado!

**Comment by luylucas10** [comment]
Mano, agradeço a ajuda, mas pelo tempo que tenho para entregar o trabalho (amanhã rsrsrsrs) eu acabei por usar o HowTo que citei na primeira postagem, acho que vai ser a solução.

Obrigado
