### ISSUE TITLE
\citetext causando "Undefined control sequence" por causa de formatação no bbl gerado

### ISSUE THREAD

**Issue by ranophoenix** [abntex/abntex2#179]
## Problema/Erro

Para reportar seu problema forneça as informações abaixo:

**Qual o sistema operacional e versão que está utilizado**?

Windows 10

**Qual versão do latex está utilizando**? (`latex --version`)

MiKTeX-pdfTeX 2.9.6211 (1.40.17) (MiKTeX 2.9.6210 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2016 Han The Thanh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.52.1; using libcurl/7.52.1 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with jpeg version 9.2
compiled with liblzma version 50020022; using 50020022
compiled with libpng version 1.6.28; using 1.6.28
compiled with libressl version LibreSSL 2.4.4; using LibreSSL 2.4.4
compiled with MiKTeX Application Framework version 1.6211; using 1.6211
compiled with MiKTeX Core version 1.6216; using 1.6216
compiled with MiKTeX Archive Extractor version 1.6211; using 1.6211
compiled with MiKTeX Package Manager version 1.6218; using 1.6218
compiled with poppler version 0.50.0
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.10; using 1.2.10

**Você está utilizando alguma personalização**? Qual?
Não.

### Descrição do problema

Erro ao compilar:

Undefined control sequence. \emph{Nome do Journal}, 2017.}

Aparentemente, o problema ocorre porque o comando não está tratando a formatação (\emph) inserida pelo arquivo bbl:

```tex
\providecommand{\abntreprintinfo}[1]{%
 \citeonline{#1}}
\setlength{\labelsep}{0pt}\begin{thebibliography}{}
\providecommand{\abntrefinfo}[3]{}
\providecommand{\abntbstabout}[1]{}
\abntbstabout{v-1.9.6 }

\bibitem[Autor 2017]{teste2017}
\abntrefinfo{Autor}{AUTOR}{2017}
{AUTOR, N. do. Example.
\emph{Nome do Journal}, 2017.}

\end{thebibliography}
```

### Passos para reprodução do problema

exemplo.tex

```tex
\documentclass[11pt]{beamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[portuguese]{babel}
\usetheme{default}
\usepackage{hyperref}
\usepackage[alf]{abntex2cite}
\begin{document}
	\begin{frame}
		\frametitle{Teste}
		\citetext{teste2017}
		\bibliography{references}
	\end{frame}
\end{document}
```
references.bib

```tex
@article{teste2017,
	title={Example},
	author= "Nome do Autor",
	journal={Nome do Journal},
	year={2017}
}
```

**Comment by ycherem** [comment]
Isso está acontecendo porque `\citetext` não é um comando do `abntex2-cite.` Use `\citeonline` e o problema desaparece.

**Comment by ranophoenix** [comment]
A questão é pq preciso da citação completa. O citeonline não fornece isso.

**Comment by ranophoenix** [comment]
A seção 4.1.3 [1] mostra o citetext como comando do abntex2-cite.  No código:

https://github.com/abntex/abntex2/blob/07466b28f311f7fc5224d9d8be7e812240ecc47e/doc/latex/abntex2/abntex2cite.tex#l492

[1]http://tug.ctan.org/macros/latex/contrib/abntex2/doc/abntex2cite.pdf

**Comment by ycherem** [comment]
Tem razão. É um problema com `\citetext`, `abntex2-cite` e `beamer` (o problema não ocorre com outras classes). Sugeriria utilizar o pacote `biblatex-abnt` já que não há previsão de modificação do estilo .bst/pacote `abntex2-cite`:

```
\documentclass[11pt]{beamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[brazil]{babel}
\usetheme{default}
\usepackage{hyperref}
\usepackage[backend=biber, style=abnt]{biblatex}
\addbibresource{references.bib}


\begin{document}
	\begin{frame}
		\frametitle{Teste}
		\fullcite{teste2017}
		\printbibliography
	\end{frame}
\end{document}
```
