### ISSUE TITLE
Dependência no \larger do relsize

### ISSUE THREAD

**Issue by GuilhermeHideki** [abntex/abntex2#180]
## Problema/Erro

Quando fui testar o biblatex-abnt, tive um problema com os apêndices.
Testei com a versão dos templates (v1.7.1?) e funcionava.
Já quando copiei a v1.9.6 aparecia um error,
mas parecia ter funcionado.

### Descrição do problema
Acredito que seja devido a dependência do `relsize`, como na issue #109.
Caso seja necessário retirar o `\larger` e trocar por outra, acho e que é esta linha:
[abntex2.cls#L522](https://github.com/abntex/abntex2/blob/master/tex/latex/abntex2/abntex2.cls#L522)

Estou utilizando via sharelatex, mas acredito que não faça diferença neste caso.
Temporariamente incluí o pacote, para que compilasse corretament.

**Comment by laurocesar** [comment]
obrigado, @GuilhermeHideki . Incluído na versão 1.9.7
