### ISSUE TITLE
Problema com lista de quadros

### ISSUE THREAD

**Issue by JFJesus** [abntex/abntex2#182]
Olá, estou tentando gerar uma lista de quadros, para isso, usei o tutorial descrito em https://github.com/abntex/abntex2/wiki/HowToCriarNovoAmbienteListing
   Porém, encontro o seguinte erro: "Missing \begin{document}. newfloat[cha..."

   Estou no ubuntu, usando XeLaTeX. Estou usando a personalização do IPT-Abntex.

   Obrigado.

**Comment by ycherem** [comment]
Envie um exemplo mínimo compilável com link para IPT-ABNTEX. Se o erro ocorre somente com a personalização, e não com a classe `abntex2`, entre em contato com o criador e/ou poste sua pergunta no fórum [Latex-br](https://groups.google.com/forum/#!forum/latex-br) ou outros.

**Comment by JFJesus** [comment]
Ok, obrigado!
