### ISSUE TITLE
Citação em Ingles

### ISSUE THREAD

**Issue by pedrobraz1990** [abntex/abntex2#185]
Eu incluo o pacote no documento utilizando:

```
\usepackage[alf]{abntex2cite}	
\selectlanguage{English}
```

E ainda assim, quando eu faço uma citação utilizando `\citeonline{}` a referência sai algo do tipo

> Autor1 e Autor2 (ano)

ao invés de:

> Autor1 and Autor2 (ano)

alguma idéia de como fazer esta alteração ?

**Comment by ycherem** [comment]
https://groups.google.com/forum/#!msg/latex-br/RA86vYeepvQ/UbgWhAEensQJ

**Comment by rodrigovimieiro** [comment]
Alguma solução que não envolva mexer no "**abntex2-alf.bst**"? Estou utilizando o Overleaf.
