### ISSUE TITLE
Autores com nome em Polonês

### ISSUE THREAD

**Issue by gabrielcaixeta** [abntex/abntex2#186]
## Problema/Erro

**Utilizo o template do abntex2 personalizada para a [UDESC](https://github.com/luisbilecki/udesc-abntex)**

### Descrição do problema

Na minha lista de referências tenho alguns autores que possuem o nome em polonês, como é o caso de **Jovan Popović** escrito em letra minúscula no arquivo bibtex, porém nas citações ou na lista de referências ele não converte o **ć** para maiúsculo, na tentativa de resolver o problema, adicionei idioma polonês (polish) como mostrado abaixo:

```tex
\documentclass[
	12pt,				
	openright,			
	oneside,			
	a4paper,			 
	chapter=TITLE,		
	section=TITLE,		
	% -- opções do pacote babel --
	french,
	polish,
	english,			
	brazil,				
	]{abntex2}
```
Quando fiz isso o latex mostra o seguinte err:
![image](https://user-images.githubusercontent.com/8334460/27603296-142abe36-5b4c-11e7-9058-db98d522a613.png)

Quando retiro este idioma:
```tex
\documentclass[
	12pt,				
	openright,			
	oneside,			
	a4paper,			 
	chapter=TITLE,		
	section=TITLE,		
	% -- opções do pacote babel --
	french,
	english,			
	brazil,				
	]{abntex2}
```
O pdf é gerado sem erros: porém minhas referências e citações ficam com problemas aparencendo assim **POPOVIć**.

Já fiz várias pesquisas ainda não cheguei a uma solução.
Alguém tem alguma ideia o por quê disto está acontecendo?

**Comment by dbmrq** [comment]
Não sei sobre o abntex2cite, mas acredito que com o [biblatex-abnt](https://github.com/abntex/biblatex-abnt) e utf8 você não teria esse problema.

**Comment by gabrielcaixeta** [comment]
Certo @dbmrq vou realizar as modificações seguindo sua sugestão e retorno sobre  o que aconteceu.

**Comment by gabrielcaixeta** [comment]
Olá, realizando alguns testes no abntex2cite percebi que estava escrevendo errado no arquivo bibtex eu estava colocando **\'{c}** ou  **ć**. Resolvi escrever assim: Popovi**\'c**. Agora está funcionando.
