### ISSUE TITLE
Letras com acentos ficam minúsculas nas citações

### ISSUE THREAD

**Issue by erickrf** [abntex/abntex2#190]
Quando um nome em uma citação possui acentos, as letras acentuadas ficam minúsculas. Esse problema é o mesmo de uma [outra issue migrada](https://github.com/abntex/abntex2/issues/54), mas cuja resposta aponta para um link morto.

**Comment by hildogjr** [comment]
Sim, isso também ocorre comigo.

**Comment by hildogjr** [comment]
Correto, obrigado.
Acredito que isso também poderia ser corrigido com a correta inclusão do encoder `\usepackage[utf8]{inputenc}` na biblioteca `abntex2cite`, visto que já se destina a usuários de uma língua que possui esses acentos.
