### ISSUE TITLE
Erro em citação com sufixo no nome do autor

### ISSUE THREAD

**Issue by hildogjr** [abntex/abntex2#192]
Estou utilizando TexLive no Ubuntu, últimas versões oficiais dos pacotes para o Debian.

Ao se criar uma referência em uma arquivo `.bib` contendo uma autor com sufixo no nome, exemplo `SOBRENOME JUNIOR, NOME` ou `SOBRENOME FILHO, NOME`, o autor é citado e listado na lista de referências como `JUNIOR, N. S.`.

Essa não é a forma correta segundo a ABNT, visto que isto não representa o verdadeiro sobrenome do autor.

Além isso, caso seja `SOBRENOME JÚNIOR, NOME` com `Ú`, este é transformado em `ú` conforme relatado no issue #190.

**Comment by cauachagas** [comment]
A solução está em [Linha 632 - abntex2cite](/abntex/abntex2/blob/master/doc/latex/abntex2/abntex2cite.tex#L632)

Quanto a acentuação, pode ser contornado com {\\' U} (embora eu também ache chato ficar fazendo isso). Creio que também é aceito o uso de Jr.
  
Além disso, deve-se tomar cuidado com as opções do abntex2cite, mais precisamente o "abnt-last-names" 

\usepackage{%
alf, % sistema autor data
abnt-last-names= abnt % ou bibtex   % Forma de como serão tratados os sobrenomes
]{abntex2cite}


Em [Linha 1545 - abntex2cite](https://github.com/abntex/abntex2/blob/master/doc/latex/abntex2/abntex2cite.tex#L1545l) há comentários sobre.
