### ISSUE TITLE
Não adicionando o ano na citação

### ISSUE THREAD

**Issue by hildogjr** [abntex/abntex2#193]
## Problema/Erro
Usando a versão 1.9.6 do abntex2cite, não está adicionando ano nas citações.

### Descrição do problema

```tex

# Definição do pacote
\usepackage[alf,abnt-etal-cite=2,abnt-etal-list=0,abnt-etal-text=emph]{abntex2cite}

# Referência
@article{_aircraft_2004,
	title = {Aircraft electric power characteristics ({{MIL}-{STD}-704F})},
	url = {http://www.wbdg.org/ccb/FEDMIL/std704f.pdf},
	shorttitle = {{MIL}-{STD}-704F},
	journaltitle = {Department of Defense Interface Standard},
	date = {2004-03-12}
}
```

Caso uso a referência como

```tex
@article{_aircraft_2004,
	
	
	
	year = 2004
        month = 03
        day = 12
}
```
funciona. Como corrigir isso sem ter que alterar todas referências manualmente?

**Comment by edusantana** [comment]
Verifique a documentação do [abntex2cite](http://ctan.sharelatex.com/tex-archive/macros/latex/contrib/abntex2/doc/abntex2cite.pdf).

Eu acredito que o ano deve ser fornecido com `year={2004}`, como no segundo exemplo. Ele não extrai o valor de ´date´ conforme sua primeira opção.

**Comment by hildogjr** [comment]
Sim, eu entendi testando isso.

Mas com certeza é uma coisa que poderia ser aperfeiçoada. Caso não encontre o campo `date` para extrair o ano, use `year`. Pois, a maioria das ferramentas de gerenciamento de referência e sites de publicações exportam para bibtex usando o campo `date`.

**Comment by edusantana** [comment]
Recomendo consultar https://github.com/abntex/biblatex-abnt
