### ISSUE TITLE
Como agrupar referências no modo numérico (ex. (1-4) em vez de (1,2,3,4))

### ISSUE THREAD

**Issue by carlos-ms-lobo** [abntex/abntex2#194]
Boa tarde, não sei se esta questão já foi colocada antes mas preciso usar o pacote abntex2cite e ser capaz de agrupar referências consecutivas múltiplas. 
Precisaria que ficasse assim:
 "aqui algum texto que requer referencia (1-4)"
Ao invés de:
 "aqui algum texto que requer referencia (1,2,3,4)"

Tem alguma opção que me permita fazer isso?

Obrigado

**Comment by dbmrq** [comment]
Não sei quanto ao abntex2cite, mas cabei de atualizar o [biblatex-abnt](https://github.com/abntex/biblatex-abnt) com essa opção. Se quiser usá-lo, você vai ter que instalar a última versão manualmente a partir do repositório e usar o estilo `abnt-numeric` com a opção `comp`:

```tex
\documentclass{article}
\usepackage{filecontents}
\usepackage[style=abnt-numeric, comp]{biblatex}

\begin{filecontents}{\jobname.bib}
  @book{one, author = {teste}, title = {teste}, date = {2018}}
  @book{two, author = {teste}, title = {teste}, date = {2018}}
  @book{three, author = {teste}, title = {teste}, date = {2018}}
  @book{four, author = {teste}, title = {teste}, date = {2018}}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

    \cite{one,two,three,four}

    \cites{one}{two}{three}{four}

    \parencite{one,two,three,four}

    \parencites{one}{two}{three}{four}

    Lala\footcite{one,two,three,four}

    Lala\footcites{one}{two}{three}{four}

    Lala\smartcite{one,two,three,four}

    Lala\smartcites{one}{two}{three}{four}

    Lala\supercite{one,two,three,four}

    Lala\supercites{one}{two}{three}{four}

    \textcite{one,two,three,four}

    \textcites{one}{two}{three}{four}

\end{document}
```

<img width="750" alt="captura de tela 2018-01-19 as 16 50 37" src="https://user-images.githubusercontent.com/15813674/35166404-ef0c2d58-fd38-11e7-9baf-9e9ff929632e.png">

**Comment by carlos-ms-lobo** [comment]
Muito obrigado!

Funcionou!

**Comment by gabriellnuness** [comment]
Estou com este problema aqui também, porém percebi que o abntex2 agrupa as citações normalmente se eu não utilizo o pacote hyperref junto.
Tem algum jeito de fazer os dois funcionarem juntos?
