### ISSUE TITLE
Generates problems with hyperref.sty.

### ISSUE THREAD

**Issue by jvhemmer** [abntex/abntex2#195]
https://github.com/abntex/abntex2/blob/8f2109ac2ef986b15d97d0bfc489b251918f1761/tex/latex/abntex2/abntex2cite.sty#L547-L548

**Comment by laurocesar** [comment]
@jvhemmer , poderia explicar qual o problema ou qual é a sua ideia? Obrigado!

**Comment by laurocesar** [comment]
Relacionado com #187
