### ISSUE TITLE
Erro no abntex2-modelo-trabalho-academico.aux

### ISSUE THREAD

**Issue by mattmarq** [abntex/abntex2#196]
## Problema/Erro

Para reportar seu problema forneça as informações abaixo:

Windows 10
MikTex 2.9 Atualizado + Texnic Center
Nenhuma personalização

### Descrição do problema

Quando eu compilo o arquivo modelo trabalho acadêmico ele dá o seguinte erro: "
BibTeX> ---line 98 of file abntex2-modelo-trabalho-academico.aux
BibTeX> : \bibdata{abntex2-options, abntex2-modelo-references
BibTeX> :                                                                                          }
BibTeX> I'm skipping whatever remains of this command"

E não gera o PDF. 

```tex
% Deseja compartilhar um código latex?
% Cole aqui.

```

### Passos para reprodução do problema

- Descreva como nós podemos reproduzir o problema:

1. Atualizar o MiKTeX e baixar o Texnic Center
2. Baixar o modelo de trabalho academico
1. Compilar

- Se possível forneça comandos ou links para baixar os arquivos necessários.

## Melhoria

Você está cadastrando uma melhoria? Descreva sua melhoria!

**Comment by laurocesar** [comment]
@mattmarq verifique se está usando a versão pura disponível neste repositório do github. Utilizando a versão mais recente do TeX, não surge mensagem de erro.
