### ISSUE TITLE
Bibliography strings 'sineloco' e 'sinenomine' indefinidas depois de `\selectlanguage{english}`

### ISSUE THREAD

**Issue by ggabriel96** [abntex/abntex2#202]
## Bibliography strings 'sineloco' e 'sinenomine' indefinidas depois de `\selectlanguage{english}`

Sistema Operacional: Fedora 28
`latex --version`: pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
Versão do abnTeX2: 2016/02/26 v-1.9.6
Versão do Memoir: 2016/05/16 v3.7f
Versão do Babel: 2016/04/23 3.9r
Versão do BibLaTeX: 2016/09/17 v3.6
Versão do Biber: 2.6
Personalização: não.

### Descrição do problema

Algumas referências precisam das strings 'sineloco' e 'sinenomine', que são definidas pelo abnTeX2 e funcionam para o idioma português do Brasil. Porém, ao escrever um texto em inglês, elas passam a ficar indefinidas ao executar o comando `\selectlanguage{english}` logo após o `\begin{document}`. Aparentemente isso não ocorre se não utilizarmos o `\selectlanguage{english}`, mas daí o suporte à língua inglesa fica incompleto.

Exemplo:

`main.tex`:
```tex
\documentclass[
  12pt,
  openright,
  twoside,
  a4paper,
  brazil,
  english
]{abntex2}

\usepackage[
  style=abnt-numeric,
  sorting=none
]{biblatex}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\addbibresource{bib/hardware.bib}

\titulo{Title}
\autor{Author}
\data{\today}
\instituicao{Institution}
\preambulo{Preamble}
\local{City}
\orientador[Advisor:]{Someone}

\begin{document}
\selectlanguage{english}

\pretextual

\imprimircapa

\imprimirfolhaderosto

\pdfbookmark{\contentsname}{toc}
\tableofcontents*
\clearpage

\textual

\chapter{Introduction}

Test \cite{eda_help}.

\printbibliography

\end{document}
```

`bib/hardware.bib`:
```
@INPROCEEDINGS{eda_help,
    author={J. Keshava and N. Hakim and C. Prudvi},
    booktitle={Design Automation Conference},
    title={Post-silicon validation challenges: How EDA and academia can help},
    year={2010},
    pages={3-7},
    doi={10.1145/1837274.1837278},
    month={06}
}
```

Log completo da compilação: [link](https://pastebin.com/c0CHTHyL).

**Comment by dbmrq** [comment]
Oi, @ggabriel96. Parece que você está usando versões antigas dos pacotes. Se você instalar a última versão do biblatex-abnt, ela já inclui a tradução pro inglês. Se você quiser continuar usando essa versão, você mesmo vai precisar definir as strings. O ideal é você dar uma lida na documentação do BibLaTeX, mas aqui tem um exemplo: https://tex.stackexchange.com/a/242268/102699

Se você encontrar mais algum problema, abra a issue no repositório do biblatex-abnt, por favor: https://github.com/abntex/biblatex-abnt

Assim fica mais fácil de organizar as questões.

**Comment by ggabriel96** [comment]
Oi @dbmrq, putz, na real eu tô com a última versão do TeX Live disponível pro Fedora (que sempre mantém tudo bem atualizado)... tanto que eu cheguei a olhar o repositório do biblatex-abnt e vi as strings lá e por isso achei que o problema era aqui (falei que elas são definidas pelo abntex2 no post original, foi um engano meu na hora de escrever). Mas de fato, vários dos meus pacotes estão desatualizados em relação à CTAN... Isso é bem estranho... Vou ver o que posso fazer.
Obrigado aí pela ajuda e desculpe a confusão!
