### ISSUE TITLE
Ambiente alineas insere um '+' antes dos itens 

### ISSUE THREAD

**Issue by alyssoncs** [abntex/abntex2#206]
## Ambiente alineas insere um '+' antes dos itens 

**Qual o sistema operacional e versão que está utilizado**?: Debian 10
**Qual versão do latex está utilizando**?: pdfTeX 3.14159265-2.6-1.40.19
**Você está utilizando alguma personalização**? Não

### Descrição do problema

Estava utilizando a versão 1.9.6 do abntex, após atualizar para o 1.9.7 percebi um comportamento diferente ao utilizar o ambiente alineas.

Ao inserir uma alínea, automaticamente um caractere '+' é inserido em acima primeiro item.

### Passos para reprodução do problema

O código a seguir, compilado com o pdflatex apresenta o problema na minha máquina.

```tex
\documentclass{abntex2}

\begin{document}

	\begin{alineas}

		\item Primeiro.

	\end{alineas}

\end{document}

```

Aparentemente o problema não acontece caso seja uma alínea aninhada.

Segue o pdf gerado: [test.pdf](https://github.com/abntex/abntex2/files/2762408/test.pdf)

**Comment by ftapajos** [comment]
A versão nova do enumitem tem algum problema a artimética pro cálculo da margem, como atualizei literalmente na véspera do dia em que precisava entregar meu TCC, não tive muito tempo para estudar uma solução melhor, mas a pull #205 deu conta para entregar o trabaho
