### ISSUE TITLE
Sumário - apresentação tipográfica dos itens não é similar à das seções do documento.

### ISSUE THREAD

**Issue by artferreirapb** [abntex/abntex2#207]
Ao ativar a opção section=TITLE a apresentação tipográfica (maiúsculas) não é repassada aos ítens do sumário. O mesmo acontece ao redefinir o tamanho das fontes (\ABNTEXsectionfontsize, \ABNTEXsubsectionfontsize, etc.) dos ítens do sumário (6.2 da NBR 6027:2012).

**Comment by laurocesar** [comment]
Isso não é um erro, é um comportamento esperado
