### ISSUE TITLE
bibliografia numerada e em ordem alfabética

### ISSUE THREAD

**Issue by tmelorc** [abntex/abntex2#209]
Como fazer para que a bibliografia seja feita em ordem alfabética, porém numerada?
Ou seja, quero a formatação como no `\bibliographystyle{abntex2-num}` porém, não na ordem em que foram citadas no texto, mas sim em ordem alfabética do sobrenome.

É possível?

**Comment by laurocesar** [comment]
Sugiro perguntar no grupo http://groups.google.com/group/latex-br
