### ISSUE TITLE
Fontes alternativas à Times New Roman e Arial

### ISSUE THREAD

**Issue by Xinayder** [abntex/abntex2#211]
Gostaria de sugerir que pudesse ter um fallback ou uma opção de escolha para a fonte do documento que será escrito com o abntex. As fontes das famílias Times e Arial estão disponíveis em outros sistemas além do Windows, mas é preciso instalá-las, além de que a licença delas não permite o uso em outros sistemas a não ser o Windows. Por isso, foram criadas fontes alternativas mas que possuem uma métrica igual, para maximizar a compatibilidade entre as famílias de fontes.

No caso, as mais famosas são a Liberation Sans, que substitui a Arial; Liberation Serif, que substitui a Times New Roman; e a Liberation Mono, que substitui a Courier New. Existem outras famílias que substituem outras fontes que são muito usadas também, como, por exemplo, a Carlito, que substitui a Calibri.

O que proponho é utilizá-las se as fontes Arial e Times não forem encontradas, mas não sei como isso funciona no LaTeX. Talvez poderia haver uma configuração que permite a alteração das fontes utilizadas no documento.

![](https://upload.wikimedia.org/wikipedia/commons/0/06/Font_Comparison_-_Liberation_Sans_to_Arial.svg)

![](https://upload.wikimedia.org/wikipedia/commons/7/75/Font_Comparison_-_Liberation_Serif_to_Times_New_Roman.svg)

https://www.vivaolinux.com.br/dica/Fontes-truetype-livres

**Comment by Ar-Kan** [comment]
Uma boa pergunta

Pesquisando sobre o assunto, acredito que seja viável, no entanto para pdfTeX, que ainda é [utilizado pela maioria dos usuários](https://tex.stackexchange.com/a/42631/187432) é mais complicado, mas não impossível, isso poderia ser facilmente implementado através do [XeLaTeX](https://www.tug.org/xetex/) ou [LuaLaTeX](http://luatex.org/).

Isso ocorre devido à maneira como operam, diferentemente do TeX em si, [podendo usar fontes existentes no sistema](https://tex.stackexchange.com/a/72/187432), há exemplos para XeTeX [aqui](https://tex.stackexchange.com/a/53448/187432) e [aqui](https://tex.stackexchange.com/a/373127/187432) e para LuaLaTeX [aqui](https://tex.stackexchange.com/a/250350/187432)

Já para pdfTeX [aqui](https://web.archive.org/web/20171211114543/http://math.stanford.edu/~jyzhao/latexfonts.php) e [aqui](https://tex.stackexchange.com/a/88424/187432) indicam maneiras de usar fontes customizadas, [aqui](https://tex.stackexchange.com/questions/196775/check-if-fontseries-exists) e [aqui](https://latex.org/forum/viewtopic.php?t=21884) falam sobre maneiras de verificar por fontes.

Atualmente o abnTeX2 suporta tanto pdfTeX quanto XeTeX, como pode ser visto na subseção 4.7.1 (Fontes com XeLATEX) da [documentação](http://linorg.usp.br/CTAN/macros/latex/contrib/abntex2/doc/abntex2.pdf), ou mesmo na [Wiki](https://github.com/abntex/abntex2/wiki/HowToXeLaTex#usar-fontes-pr%C3%B3prias-com-xelatex), para LuaLaTeX não tenho conhecimento.

Se você busca essa funcionalidade o mais indicado seria mesmo usar XeLaTeX.

Eu não faço parte do projeto, só estou aqui de curioso, contudo, no meu entender esse tipo de suporte foge do escopo proposto ao projeto, e, para finalizar, por curiosidade, você saberia me informar em qual NRB e onde nela se encontra a especificação para usar ou Arial ou Times New Roman?

(●'◡'●)
