### ISSUE TITLE
Remover "citado na página ..." das referências

### ISSUE THREAD

**Issue by mustachius** [abntex/abntex2#213]
Olá,

ao proceder com citações no abnTeX2 e o pacote abntex2cite, obtenho como resultado:

> LIU, D. Enterotoxin-Producing Staphylococcus aureus. In: Molecular Medical
> Microbiology. Elsevier, 2015. p. 979–995. ISBN 978-0-12-397169-2. Disponível em:
> <http://linkinghub.elsevier.com/retrieve/pii/B978012397169200055X>. Citado na
> página 29.

Todavia, de acordo com as normas da minha Universidade, necessito remover "Citado na
página 29.", bem como apresentar o título do livro - nesse caso "Molecular Medical
Microbiology" em negrito:

> LIU, D. Enterotoxin-Producing Staphylococcus aureus. In: **Molecular Medical**
> **Microbiology**. Elsevier, 2015. p. 979–995. ISBN 978-0-12-397169-2. Disponível em:
> <http://linkinghub.elsevier.com/retrieve/pii/B978012397169200055X>.

Sou iniciante e estou tentando me virar, mas não encontrei maneiras de realizar estas alterações. É possível alterar?

**Comment by EduardoJM** [comment]
@mustachius 
> necessito remover "Citado na página 29.

Não sei se seria a forma mais correta de se fazer isso, mas o seguinte código no preâmbulo é funcional no meu documento:

```latex
% ---
% Configurações do pacote backref
% Usado sem a opção hyperpageref de backref
\renewcommand{\backrefpagesname}{}
% Texto padrão antes do número das páginas
\renewcommand{\backref}{}
% Define os textos da citação
\renewcommand*{\backrefalt}[4]{}%
% ---
```

> apresentar o título do livro - nesse caso "Molecular Medical Microbiology" em negrito

Ao importar o pacote `abntex2cite` use o parâmetro `abnt-emphasize=bf` como abaixo:
```latex
\usepackage[alf, abnt-emphasize=bf]{abntex2cite}
```
Acredito que essas duas soluções sirvam pra você. Abraços.
