### ISSUE TITLE
Definir número de autores na citação

### ISSUE THREAD

**Issue by hildogjr** [abntex/abntex2#216]
Como configurar para uma citação, e apenas essa, aparecer o número desejado de autores antes do "_et al._"?

Estou usando o TexStudio com último MikTex no Linux.

Minha configuração de pacotes:

    \usepackage[brazilian,hyperpageref]{backref}
    \usepackage[alf,abnt-etal-cite=2,abnt-etal-list=0,abnt-etal-text=emph]{abntex2cite}

Minha entrada:
`
@article{brandao_optimized_2016,
	title = {Optimized Compensation of Unwanted Current Terms by {AC} Power Converters under Generic Voltage Conditions},
	author = {BrandÃo, Danilo Iglesias and Guillardi, {Júnior}, Hildo and Paredes, Helmo and MarafÃo, Fernando and Pomilio, José Antenor}
}
`

Minha saída:
`\cite{brandao_optimized_2016}`
(BRANDÃO _et al._, 2016)

Eu gostaria de obter nesse caso:
(BRANDÃO, GUILLARDI Júnior,  _et al._, 2016)

**Comment by Renato2012** [comment]
Não vejo sentido em você querer essa saída, uma vez que ela estaria contrária às normas da ABNT.

**Comment by hildogjr** [comment]
Sim, sei que é fora de padrão. Mas, nessa publicação, em específico, quero evidenciar em comentar no meu texto a contribuição do segundo autor.

**Comment by Renato2012** [comment]
Ainda não vejo sentido e no meu entendimento ficaria errado.
Mas vamos lá.
Talvez você resolva isso definindo um novo comando para citar apenas o trabalho em questão (veja [isso](https://en.wikibooks.org/wiki/LaTeX/Macros)), nele você alteraria a quantidade de autores listados antes do et al. (veja [isso](https://tex.stackexchange.com/questions/69028/set-limit-to-one-author-when-using-et-al-in-biblatex)).

Espero que ajude.
