### ISSUE TITLE
Tabela com numeração errada após \imprimirlistadesimbolos 

### ISSUE THREAD

**Issue by TiagoPrata** [abntex/abntex2#217]
## Tabelas não iniciando a contagem a partir do número 1

**Qual o sistema operacional e versão que está utilizado**?
. Windows 7 e Windows 10
**Qual versão do latex está utilizando**? (`latex --version`)
. MiKTex 2.9.7000 64-bit
**Você está utilizando alguma personalização**? Qual?
. Não

### Descrição do problema

Fazendo minha dissertação tudo estava funcionando muito bem até que precisei adicionar uma tabela. A tabela em si também estava normal, porém ao invés de a numeração começar pelo número 1, elas estavam começando no 2, ou as vezes 3...
Abaixo segue um exemplo da primeira tabela que adicionei. (Assim ela já apresentava no caption 'Tabela 2', sendo que era a primeira)

```tex
\begin{table}[h]
	\centering
	\caption{Valores para modelagem \acrshort{siso} do \acrshort{tclab}}
	\label{tab:tclab_modelo_siso_valores}
	\begin{tabular}{cccc} \toprule
		{Sigla} & {Descrição}	& {Valor}	& {Valor2}	\\ \midrule
		A1 	& B1 		& C1		& D1		\\
		A2	& B2		& C2		& D2		\\
		A3	& B3		& C3		& D3		\\	
		A4	& B4		& C4		& D4		\\ \bottomrule
	\end{tabular}
\end{table}

```

Fiz algumas modificações tentando arrumar o problema, mas nada parecia adiantar... Até que resolvi tentar algo um pouco mais 'extremo' e adicionei um
```tex
\setcounter{table}{0}
```
antes da tabela. Funcionou! :)

Então fui mudando o posicionamento desse comando 'setcounter' até que encontrei o local exato onde ele começava a funcionar: logo após o \imprimirlistadesimbolos... Qualquer lugar que eu adicione esse comando antes disse as tabelas voltam a ficar com a numeração errada.

Alguém saberia dizer se o '\imprimirlistadesimbolos' pode impactar de alguma forma na contagem das tabelas?

### Passos para reprodução do problema

Não sei exatamente como reproduzir o problema, pois ele aconteceu já na primeira vez que adicionei uma tabela ao texto

## Melhoria

A solução para mim foi adicionar os comandos conforme descrevi acima, então no final ficou:
```tex
\imprimirlistadesimbolos 
\setcounter{table}{0}
```

**Comment by EduardoJM** [comment]
> Alguém saberia dizer se o '\imprimirlistadesimbolos' pode impactar de alguma forma na contagem das tabelas?
Sei que já solucionou, mas respondendo a sua pergunta: sim, caso o comando `\imprimirlistadesimbolos` utilize uma tabela, o que eu acredito que aconteça, dado a solução que comentou.

**Comment by TiagoPrata** [comment]
Olá, @EduardoJM,
Obrigado pela resposta.
Na verdade não encaro que eu tenha dado uma solução, eu chamaria de 'workaround'. Hehe

Se houver um jeito mais elegante de resolver, acho que seria melhor.

**Comment by EduardoJM** [comment]
> Se houver um jeito mais elegante de resolver, acho que seria melhor.

Pra isso, teria que ver que código você está usando, não encontrei o comando `\imprimirlistadesimbolos` em nenhum dos exemplos aqui. Mas dificilmente a solução iria fugir disso `\setcounter{table}{0}`.

**Comment by TiagoPrata** [comment]
> Pra isso, teria que ver que código você está usando, não encontrei o comando `\imprimirlistadesimbolos` em nenhum dos exemplos aqui. Mas dificilmente a solução iria fugir disso `\setcounter{table}{0}`.

Tem razão @EduardoJM, eu achei que este era um comando padrão do abntex2, mas me enganei.
O comando `\imprimirlistadesimbolos` está no arquivo [anbtex2-glossario.sty](https://files.gitter.im/abntex/limarka/EK4F/anbtex2-glossario-style.zip) que encontrei em um [fórum](https://gitter.im/abntex/limarka?at=5a5977ab6117191e615cc817).
Esse style traz alguns comandos para trabalhar com siglas, símbolos e criar seus respectivos glossarios, porém apesar de ter sido bem útil pra mim, não faz parte do pacote core.

**Comment by ronayde** [comment]
Estava com o mesmo problema, obrigado por ajudar a solucionar.
