### ISSUE TITLE
Impedir impressão de título estrangeiro

### ISSUE THREAD

**Issue by italovieira** [abntex/abntex2#218]
Uma dúvida: como que faço para impedir que seja imprimido o 
`\tituloestrangeiro`?

Se eu tentar apenas remover a linha, ocorre erro ao gerar o documento.

**Comment by edusantana** [comment]
```tex
\renewcommand{\tituloestrangeiro}{}
```

Isso funciona?

**Comment by italovieira** [comment]
Não funciona. Acontece o seguinte:

```
(./document.aux)
(/usr/share/texmf-dist/tex/latex/lm/t1lmr.fd)
(/usr/share/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(/usr/share/texmf-dist/tex/latex/microtype/mt-cmr.cfg)
! Undefined control sequence.
<recently read> \theforeigntitle

l.191
```

**Comment by EduardoJM** [comment]
@italovieira 

> ! Undefined control sequence.
> <recently read> \theforeigntitle

O erro diz que o comando \theforeigntitle não foi reconhecido, isso porque ele é definido dentro do comando \tituloestrangeiro da classe abntex2. Veja se inserindo isso no preâmbulo resolve:
```
\ifthenelse{\equal{\ABNTEXisarticle}{true}}{%
\renewcommand{\maketitlehookb}{}
}{}
```
Aqui, utilizando o modelo de artigo deste repositório ficou assim:
![Captura de tela de 2019-07-09 17-19-36](https://user-images.githubusercontent.com/20397491/60920111-cca4d400-a26d-11e9-983b-184506dbc50f.png)

**Comment by caioaguida** [comment]
> @italovieira
> 
> > ! Undefined control sequence.
> >  \theforeigntitle
> 
> O erro diz que o comando \theforeigntitle não foi reconhecido, isso porque ele é definido dentro do comando \tituloestrangeiro da classe abntex2. Veja se inserindo isso no preâmbulo resolve:
> 
> ```
> \ifthenelse{\equal{\ABNTEXisarticle}{true}}{%
> \renewcommand{\maketitlehookb}{}
> }{}
> ```
> 
> Aqui, utilizando o modelo de artigo deste repositório ficou assim:
> ![Captura de tela de 2019-07-09 17-19-36](https://user-images.githubusercontent.com/20397491/60920111-cca4d400-a26d-11e9-983b-184506dbc50f.png)

Ninguém nunca de respondeu, mas resolve, acabei de usar aqui.
