### ISSUE TITLE
Numeração de páginas no Sumário e nas listas de figuras/tabelas (resolvido - nada a fazer)

### ISSUE THREAD

**Issue by cantao** [abntex/abntex2#219]
## Sumários e listas de figuras/tabelas longos ficam sem numeração da primeira página

- SO: Debian 10 Buster stable
- XeTeX 3.14159265-2.6-0.99999

A primeira página de um sumário, lista de tabelas ou de figuras fica sem numeração de página. Páginas subsequentes são numeradas normalmente.

### Passos para reprodução do problema

1. Use `\tableofcontents`, `\listoffigures` ou `\listoftables` no documento
1. Compile com `xelatex doc.tex`
1. Verifique que a primeira página destas seções está sem numeração

**Comment by edusantana** [comment]
Pode prover um exemplo mínio que mostre isso?

**Comment by cantao** [comment]
Certamente!

Eu usei o pacote `pgffor` para automatizar a geração das seções. Eu testei manualmente com vários `\section` e o efeito é o mesmo. Note que a primeira página do Sumário **não** aparece numerada.

```tex
\documentclass[article,sumario=tradicional]{abntex2}

\usepackage{pgffor}

\begin{document}

\pagestyle{plain}
\thispagestyle{plain}

\tableofcontents

\clearpage

\foreach \n in {1,2,...,50}{\section{Foo \n}}

\end{document}
```
Muito obrigado!

**Comment by edusantana** [comment]
Oi @cantao eu fui olhar a norma:

ABNT NBR 14724 - Terceira edição (17.03.2011):

![paginacao](https://user-images.githubusercontent.com/3603111/62463009-480b7f80-b75f-11e9-8f41-36a2ba0be854.png)

Na minha interpretação, se não mostrar a página no sumário fica esquisito, porém de acordo com as normas.

**Comment by cantao** [comment]
Oi @edusantana, obrigado pela atenção!

Pois é, também acho bem esquisito, mas fazer o quê, bora seguir a norma.

Mais uma vez obrigado!
