### ISSUE TITLE
"nonumchapter" não é exibido no Sumário

### ISSUE THREAD

**Issue by lincolnaps** [abntex/abntex2#228]
## Problema/Erro

Para reportar seu problema forneça as informações abaixo:

**Qual o sistema operacional e versão que está utilizado**?
Overleaf
**Qual versão do latex está utilizando**? (`latex --version`)
**Você está utilizando alguma personalização**? Qual?

### Descrição do problema

Capítulos inseridos sem numeração (\chapter*{}) não aparecem no Sumário, mas a página é exibida com o título centralizado no cabeçalho.

```tex
% Deseja compartilhar um código latex?
% Cole aqui.

```

### Passos para reprodução do problema

- Descreva como nós podemos reproduzir o problema:

1. Passo 1
1. Passo 2
1. Passo 3

- Se possível forneça comandos ou links para baixar os arquivos necessários.

## Melhoria

Você está cadastrando uma melhoria? Descreva sua melhoria!

**Comment by laurocesar** [comment]
Fechando porque esse é o resultado esperado
