### ISSUE TITLE
correção da sessão Apêndice

### ISSUE THREAD

**Issue by vidalcenter** [abntex/abntex2#234]
## Problema/Erro

Para reportar seu problema forneça as informações abaixo:

**Qual o sistema operacional e versão que está utilizado**?
**Qual versão do latex está utilizando**? (`latex --version`)
**Você está utilizando alguma personalização**? Qual?

### Descrição do problema
"Apêndices" o correto seria "Apêndice" no singular como posso realizar essa correção no pacote abnTeX

**Comment by laurocesar** [comment]
@vidalcenter , isso não é um erro, pois trata-se de uma parte do documento.

De toda forma, se quiser trocar o nome, basta uar:

  \renewcommand{\apendicesname}{Apêndice alterado}
