### ISSUE TITLE
desabiliar 'disponível em' e 'citado na página'

### ISSUE THREAD

**Issue by 255ribeiro** [abntex/abntex2#237]
## Pergunta/question
Boa Tarde

Para atender um edital de projeto de pesquisa, preciso desabilitar as informações 'disponível em:' e 'citado na página:' das referências. Alguém pode me ajudar com essa configuração?

estou usando o modelo de artigo: [https://github.com/abntex/abntex2/blob/master/doc/latex/abntex2/examples/abntex2-modelo-artigo.tex](https://github.com/abntex/abntex2/blob/master/doc/latex/abntex2/examples/abntex2-modelo-artigo.tex)

**Comment by laurocesar** [comment]
@255ribeiro , sugiro postar a dúvida no grupo https://groups.google.com/d/forum/latex-br
