### ISSUE TITLE
Como gerar um PDF/A utilizando o abntex2?

### ISSUE THREAD

**Issue by mvlp** [abntex/abntex2#239]
Recentemente me deparei com essa nova "norma" que está sendo adotada em muitas universidades. Entretanto não consegui gerar um PDF/A usando o pacote pdfx e o abntex juntos, alguma dica?

**Comment by laurocesar** [comment]
Na wiki ha uma página sobre isso.

**Comment by salvadorfsc** [comment]
mvlp, você conseguiu resolver o problema com o pdf/A-1B?

**Comment by salvadorfsc** [comment]
laurocesar, você olhou o que diz a wiki?
"Em breve".
