### ISSUE TITLE
Como deixar o título em negrito, nas referências e remover o "Nenhuma citação no texto" ao usar o \nocite?

### ISSUE THREAD

**Issue by VitorTRiker** [abntex/abntex2#240]
Olá a todos, 

Eu queria saber se é possível deixar em negrito o título dos trabalhos, artigos e etc.. nas referências, bem como remover o "nenhuma citação no texto" após usar a função \nocite no latex?

`ALDA, E.; GIMÉNEZ, V.; PRIOR, D. Does a complex environment affect police efficiency: anexamination on municipal police in mexico.Applied Economics Letters, Taylor & Francis,v. 27, n. 14, p. 1220–1223, 2020. Nenhuma citação no texto.`

Além do exposto, queria saber também se possível alinhar à esquerda e deixar maísculo o título da seção referência?

Desde já, agradeço a qualquer resposta que me ajude nesta aventura que se chama latex.

**Comment by EduardoJM** [comment]
@VitorTRiker Sobre as referências, acredito que esse issue aqui responda sua dúvida:

https://github.com/abntex/abntex2/issues/213#issuecomment-490633751

**Comment by vladyryuricavalcanti** [comment]
> Olá a todos,
> 
> Eu queria saber se é possível deixar em negrito o título dos trabalhos, artigos e etc.. nas referências, bem como remover o "nenhuma citação no texto" após usar a função \nocite no latex?
> 
> `ALDA, E.; GIMÉNEZ, V.; PRIOR, D. Does a complex environment affect police efficiency: anexamination on municipal police in mexico.Applied Economics Letters, Taylor & Francis,v. 27, n. 14, p. 1220–1223, 2020. Nenhuma citação no texto.`
> 
> Além do exposto, queria saber também se possível alinhar à esquerda e deixar maísculo o título da seção referência?
> 
> Desde já, agradeço a qualquer resposta que me ajude nesta aventura que se chama latex.

é possível deixar em negrito: **abnt-emphasize=bf** no pacote {abntex2cite}

\usepackage[
			alf,
			**abnt-emphasize=bf,**
			abnt-etal-list=99,
			abnt-etal-text=emph,
			abnt-full-initials=yes
			]{abntex2cite}	                 % Citações padrão ABNT
