### ISSUE TITLE
Link para download na Wiki está invalido

### ISSUE THREAD

**Issue by guilhermedelyra** [abntex/abntex2#244]
O link disposto na wiki [http://dl.bintray.com/laurocesar/generic/abntex2-modelos-1.9.7.zip](http://dl.bintray.com/laurocesar/generic/abntex2-modelos-1.9.7.zip) está indisponível:

![image](https://user-images.githubusercontent.com/23236957/117870846-08968f00-b273-11eb-9aea-7624afefedb1.png)

Aparentemente, a Bintray está migrando pra JFrog...

**Comment by laurocesar** [comment]
Resolvido, apontando para o CTAN
