### ISSUE TITLE
Estilos bibliográficos com biblatex

### ISSUE THREAD

**Issue by GoogleCodeExporter** [abntex/abntex2#25]
```
What is the task?
Desenvolver estilos bibliográficos com biblatex

What is the final product?
Estilos bibliográficos em biblatex compatíveis com as normas da ABNT, 
especialmente ABNT NBR 6023:2002 e ABNT NBR 10520:2002.

Where should it be put?
Enquanto os estilos estiverem sendo desenvolvidos e não estiverem estáveis, 
os produtos devem ser armazenados no respositório do projeto em 
/contrib/biblatex

Additional information:
O biblatex-abnt é baseado no trabalho de Henrique Pasti de 
https://bitbucket.org/hbpasti/biblatex-abnt/
```

Original issue reported on code.google.com by `laurocesar` on 17 Jan 2013 at 1:27

**Comment by danielbmarques** [comment]
Ninguém mais está trabalhando nisso?
Eu fiz algumas melhorias nesse último arquivo aí em cima, enviado pelo `dudekt…@gmail.com`. Atualizei algumas coisas que mudaram na última atualização do biblatex; os sobrenomes não estavam aparecendo em maiúsculas, por exemplo. E também acrescentei uma opção para que os títulos possam ficar em negrito ou em itálico, dependendo de como o usuário preferir. Mas ainda tem bastantes coisas pra arrumar… pelo que eu vi ainda não tem um comando equivalente ao `\citeonline`, por exemplo. Seria legal se mais gente pudesse ajudar. Posso postar meu código aqui, mas daí eu faço o que, crio um repositório meu? Aqui não tem um branch pra desenvolvimento, né?

**Comment by ycherem** [comment]
Seria bom fazer um novo repositório dentro do projeto abntex para que possamos testar. Os maiúsculos eu só não consegui para os autores na bibliografia, no texto sim.

**Comment by danielbmarques** [comment]
Acho que é uma boa mesmo. Ainda estou mudando muitas coisas aqui, as entradas `inbook` e `incollection` estavam bem diferentes do que deveriam, acabei de arrumar isso, e também vários outros detalhezinhos menores. Eu já tinha acrescentado a opção de colocar os títulos em negrito e em itálico, agora acrescentei uma opção pra usar ou não versalete também. Quando tiver um repositório ou um branch eu coloco meu código aqui. Ou então faço um repositório meu quando tiver um tempo.

**Comment by ycherem** [comment]
Pode incluir seu código neste repositório: https://github.com/abntex/abntex2-biblatex

**Comment by danielbmarques** [comment]
@ycherem Pronto! 🎉 
Por enquanto só mexi no `.bbx`. Talvez tenha jeitos melhores de fazer as coisas que eu fiz, eu não sabia nada sobre nada disso, estou aprendendo agora meio na marra. Mas o driver do `incollection` que eu acrescentei ficou bem legal pelo que estou vendo, agora a gente precisa checar outros tipos de entradas. Também coloquei as opções `bftitles` e `scbib` pra mostrar os títulos em negrito e pra usar versalete, respectivamente.

Ó, uma entrada `book` e uma `incollection` usando as duas opções:

![captura de tela 2016-04-22 as 17 56 45](https://cloud.githubusercontent.com/assets/15813674/14754743/b1314f20-08b3-11e6-9537-3fc52452f75a.png)

**Comment by ycherem** [comment]
@danielbmarques 
Não quer fazer um upload dos seus testes [aqui](https://github.com/abntex/abntex2-biblatex)?

**Comment by danielbmarques** [comment]
@ycherem 
Coloquei [lá](https://github.com/abntex/abntex2-biblatex) [um arquivo que cita todas as entradas do manual do abntex2cite](https://github.com/abntex/abntex2-biblatex/blob/master/abnt-testcase.pdf).
Já vi que tem várias coisas erradas. Agora só precisamos olhar as entradas uma por uma e mudar o que for preciso. Vai ser fácil, são só 18 páginas, rs.

**Comment by ycherem** [comment]
Daniel,

Está ficando ótimo. Já dá conta da maioria dos casos!

Uma coisa é que você colocou:

\ExecuteBibliographyOptions{firstinits=true}

Talvez pudéssemos deixar por conta do autor ao escrever:

\usepackage[style=abnt,firstinits=true]{biblatex}

Você testou como ficou \parencites e \textcites?

Grande parte dos casos que faltam é colocar o título em maiúsculo quando
não houver autor.

O URL acho que poderia ser mudado com

\DeclareFieldFormat{url}{Disponível em\addcolon\space\url{#1}}

mas não testei.

Isso seria inserido no abnt.bbx?

Youssef Cherem
________________
!المسيح قام! حقاً قام

2016-04-24 5:17 GMT-03:00 Daniel Marques <notifications@github.com>:

**Comment by danielbmarques** [comment]
@ycherem 
Legal, tirei o `firstinits` e mudei o URL, seu código deu certinho, é no `.bbx` mesmo.
Agora estou vendo como fazer com os títulos quando não tem autor. Por enquanto estou com este problema: http://tex.stackexchange.com/questions/306340/make-just-part-of-titles-uppercase-with-biblatex

Depois, conforme forem aparecendo mais problemas, talvez seja melhor irmos abrindo *issues* lá no próprio repositório pras coisas que virmos que estão erradas, aí fica melhor organizado e vamos arrumando quando der.

**Comment by danielbmarques** [comment]
Comparei todas as referências uma por uma e agora o `biblatex-abnt` é capaz de reproduzir *ipsis litteris* todas as referências citadas nos dois manuais do `abntex2cite`. 🎉
Na maior parte dos casos não é preciso fazer nenhuma mudança no arquivo `.bib`. Coloquei as exceções no readme lá no repositório.

Além disso, no `biblatex-abnt` estão resolvidas as issues #56, #97, #110, #127, #135 e #155 (acho que são todas as que tem aqui a respeito das referências). 😎 

Agora, em vez de limitar o estilo a uma reprodução do `abntex2cite`, vou começar a implementar recursos específicos do `biblatex`, como o campo `crossref`. Algumas coisas já estão diferentes no [arquivo que tem lá](https://github.com/abntex/abntex2-biblatex/blob/master/abnt-testcase.pdf). Em vez de usar o campo `furtherresp`, por exemplo, mudei a bibliografia pra usar os campos `editora`, `editoratype`, `editorb`, `editorbtype` etc. Assim todas as entradas são impressas de um jeito consistente, apesar de nos manuais a ABNT colocar esses campos cada vez de um jeito (e.g. "Edição de Fulano", "Editado por Fulano", "Editor: Fulano", "Editor Fulano"). Mas o campo `furtherresp` ainda pode ser usado para deixar as entradas iguaizinhas às do manual.

**Comment by ycherem** [comment]
@danielbmarques Parabéns pelo trabalho!!! :tada: 

Se todas as referências de exemplo já podem reproduzidas, já podemos pensar em criar um pacote para divulgação.

**Comment by danielbmarques** [comment]
@ycherem Obrigado! :)

Arrumei mais uns detalhes, acrescentei um [mini manual](https://github.com/abntex/abntex2-biblatex/blob/master/biblatex-abnt.pdf) e enviei pro ctan!

**Comment by danielbmarques** [comment]
@ycherem 
Aliás, eu enviei o pacote com o nome `biblatex-abnt`, já que esse é o padrão usado por todos os estilos do `biblatex` (e.g. `biblatex-apa`, `biblatex-chicago` etc.).
Você pode mudar o nome do repositório pra `biblatex-abnt` também (ou me dar permissão pra fazer isso lá)? Assim fica mais fácil quando for atualizar no ctan, é só zipar a própria pasta do repositório.

**Comment by ycherem** [comment]
Daniel,

Parabéns pelo trabalho, vamos divulgá-lo!. Vou ver se mudo o nome do
repositório.

Youssef Cherem
________________
!المسيح قام! حقاً قام

2016-05-12 5:59 GMT-03:00 Daniel Marques <notifications@github.com>:

**Comment by laurocesar** [comment]
@danielbmarques e @ycherem !

Parabéns pelo excelente trabalho com o biblatex!

Estive de férias e não pude contribuir com o trabalho de vocês. Mas, quando me dei conta, já estava tudo pronto! Fantástico!

@danielbmarques , legal que você já mandou para o CTAN: http://www.ctan.org/pkg/biblatex-abnt

Agora precisamos pensar em um novo bundle dos modelos do abntex com o biblatex ao invés do bibtex. A ideia original era que o abntex2 chegasse à versão estável (2.0) apenas quando o biblatatex estivesse implementado. Por isso que a versão atual do abntex2 é a 1.9.6 (uma vez que partimos da versão 1.0 que já existia desde 2001). Porém, penso que o ideal seria lançar uma versão 3.0 e deixar essa versão 2.0 estável com bibtex. Vocês concordam?

Vou ajudar a verificar a saída das bibliografias e, se achar alguma coisa, vou criar issues lá no repositório do biblatex, para nos organizarmos nas contribuições.

Mais uma vez, parabéns! É ótimo ver o espírito do LaTeX sempre renovado!

Abraços!

**Comment by danielbmarques** [comment]
@laurocesar Valeu. :)
Sobre o pacote ser lançado na versão 2.0 ou 3.0 do `abntex2`, vocês é que mandam, não estou muito por dentro das outras mudanças. Acho que o maior critério é a quantidade de *breaking changes*; se as outras mudanças não forem tão grandes pode ser melhor lançar numa versão 3.0 mesmo.

**Comment by ycherem** [comment]
@laurocesar 
O mérito é todo do @danielbmarques! :clap: :wink:

**Comment by laurocesar** [comment]
Pessoal, 

Atualizei o site do abntex para incluir a informação do biblatex-abnt. Também criei um novo projeto, chamado abntex3, cujo objetivo será adaptar os modelos integrando-os ao biblatex-abnt. Também será preciso refazer todos os manuais, incluindo o que o @danielbmarques já detalhou (na verdade, ele já fez quase tudo, senão tudo...).

Vou fechar esta issue. Novas issues referentes a integração abrimos no projeto do abntex3. Novas issues do biblatex, abrimos no projeto do biblatex-abnt.

Abraços!
