### ISSUE TITLE
Link Quebrado na Página PorOndeComeçar

### ISSUE THREAD

**Issue by alvarengacarlos** [abntex/abntex2#251]
## Link quebrado na página PorOndeComecar do Github

**Ubuntu Linux Focal 20.04.03**

Na página do [GitHub PorOndeComeçar](https://github.com/abntex/abntex2/wiki/PorOndeComecar) tem um link que não está funcionado. O link problemático está descrito como: [**VisualFAQ**](http://mirrors.ctan.org/info/visualFAQ/visualFAQ.pdf) e está dando **erro 404** ou **not found**.

**Comment by EduardoJM** [comment]
@alvarengacarlos uma versão para o VisualFAQ disponível nos mirrors da CTAN: https://ctan.dcc.uchile.cl/info/visualfaq/visualFAQ.pdf

Vou ver se consigo atualizar, também, na wiki.
