### ISSUE TITLE
Número nas páginas e estilo do capítulo de referências.

### ISSUE THREAD

**Issue by jromerossj** [abntex/abntex2#255]
Olá colegas.

Estou iniciando agora no mundo do LATEX e comecei a utilizar o abntex2.

A instituição que estudo exige que o nome "Referências" seja em negrito e tamanho 12, porém não consigo editar. Já editei as seções para ficar de acordo com o padrão da instituição, porém somente "Referências" que não achei como modificar.

Outra coisa, quando não usava abntex2 as páginas eram numeradas, mas a partir do momento em que comecei a usar não achei um modo de numerá-las novamente.

Segue o modelo que a instituição pede, somente o que precisa modificar é o nome referências e incluir a numeração nas páginas:

https://pt.overleaf.com/read/tqzkythsrdtv

Alguém teria uma solução para me ajudar?

**Comment by laurocesar** [comment]
Isso é uma questão pro grupo de discussão:

https://groups.google.com/g/latex-br
